### ISSUE TITLE
How to use the "File Recovery" / Undelete functionality? (not disk image restore)

### ISSUE THREAD

**Issue by fredddii** [rescuezilla/rescuezilla#112]
I tested the file recovery by putting two test pictures on the desktop of a Windows 10 machine and removing them.

I then proceeded with the recovery, like this:
- Select the source partition
- Select the target drive
- It seemed to then proceed to dump everything to the target drive

The result was a whole bunch of random folders with random files in them. I was unable to find the deleted pictures back via name, and going through all picture files to look for these two pictures would be a tedious process.

Am I doing it wrong?

**Comment by shasheene** [comment]
Hi @fredddii,

By the way, I should have mentioned in your prior GitHub issue, the best place to receive support is the [Sourceforge support forum](https://sourceforge.net/p/rescuezilla/discussion/support/).

It sounds like you are referring to the '**File Recovery**' function under Start menu -> Other -> 'File Recovery'. This is the command-line data recovery software PhotoRec made by a company called CGSecurity. It sounds like your goal is to "undelete" an a file after deleting it. Therefore, **you don't want to be using PhotoRec, but instead want to be using TestDisk (also by CGSecurity)**. Both are provided by Rescuezilla.

TestDisk is the "undelete" program that's able to navigate to a specified path, "see" the filename which was recently deleted and restore it to exactly the same place. In contrast, PhotoRec is designed for deep scans of eg, a corrupted digital camera memory card where the goal is to extract as many image fragments as possible.

Please double-click the terminal icon on the desktop, then type 'testdisk'. Please carefully follow the prompts. Once you have done a 'Quick Search' and selected your partition, please do not press Enter (you do not need to do a 'Deeper Search') but instead press 'P' to navigate the filesystem. Once you found the deleted file you wish to restore, highlight it and press 'c'. Then navigate to the destination directory, and press 'C' when the destination is correct. My longer term goal is to create a easy-to-use _graphical_ frontend to TestDisk (task #12).

**This should fully achieve your goals. Let me know you go!**

Side notes: The only reason PhotoRec is used as the default 'File Recovery' tool is because the original _Redo Backup and Recovery_ application did that. But it doesn't actually make sense to do it like that, so I will immediately rename the shortcut 'Photo Recovery' and add a new item named 'File Recovery' that launches TestDisk. This should provide a much better user-experience for most Rescuezilla users as they will be unfamiliar with TestDisk and PhotoRec. I probably should have done this a long time ago, but I have been focused on developing Rescuezilla disk imaging functionality.

**Comment by fredddii** [comment]
I still am unable to get any viable results with these tools.

I was hoping for recovery features like DMDE provides. It pretty much is just a file explorer and allows you to pick files you want to recover, either existing or deleted. With of course the added feature of it being resilient to failing hard drives, which is why it is labelled recovery software.

If I am still doing it wrong, I would like to learn how to be able to use it in such a way. If the tool is not meant to provide these features, feel free to close the ticket.

Thanks in advance for the information and attempt to guide me.

**Comment by shasheene** [comment]
TestDisk should be able to do exactly what you want. It is **extremely** powerful, but continues to have an extremely difficult command-line interface until I complete task #102  I should have mentioned TestDisk (and the partclone utility used internally by Rescuezilla) **are not particularly resilient to failing hard drives**.

**For failing hard drives (and optical media), the best tool I have ever used is "ddrescue"**. It is a command-line tool that is extremely robust to the errors caused by dying hard drives, and is able to salvage far more blocks than other tools. ddrescue can be combined with TestDisk for file recovery. The way it works is ddrescue first reads the failing hard drive sequentially and just skips all bad sectors. Then after it the first pass is complete, it goes back and tries the bad sectors in various ways (including reading them backwards) to try and salvage the bad sectors as much as possible. Once the ddrescue backup has completed (which may take a very long time depending on how damaged a hard drive is), you then have a raw backup of your hard drive that you can load into tools like TestDisk.

There is an ddrescue GUI on the internet, but I have never used it. Rescuezilla currently only provides the ddrescue command-line interface.

Here are the step-by-step instructions:

Let's say you're trying to salvage data from a failing 1TB hard drive. You will need a second hard drive with at least 1TB to write the raw, uncompressed disk image that ddrescue creates of the failing hard drive.

1. Open GParted (Start -> Other -> GParted) and use the top-right drop-down menu to identify the device node of your failing hard drive (let's say it was /dev/sdb).
2. Close GParted.
3. Open the File Manager. Mount the _working_ hard drive (with at least eg, 1TB free space). Right-click -> "open current directory in terminal".
4. Run `ddrescue /dev/sdb myFailingHarddrive.ddrescue.img failingHDDLogFile.txt`
  * (Optional: Open a second terminal and run `dmesg -Tw` to better understand where your hard drive damage is located)
5. Wait _many_ hours for the ddrescue command to complete.
6. Run `testdisk myFailingHarddrive.ddrescue.img`. Select the "disk", partition table etc and follow the prompts (see my previous post for detailed instructions)

The above instructions should be sufficient to salvage deleted files from even failing hard drives and optical media.

For completeness, I note that it's definitely possible to mount individual partitions from the ddrescue image (with `fdisk -l myFailingHarddrive.ddrescue.img`, `mount -o loop,offset=XYZ`, and a calculator), and then navigate using a graphical file manager (rather than going through TestDisk). There are [articles](http://www.andremiller.net/content/mounting-hard-disk-image-including-partitions-using-linux) describing how to do this. Though, TestDisk is much more resilient to damaged filesystems than your average file manger.

Side note: It may be possible for TestDisk to incorrectly autodetect a traditional DOS (MBR) drive as a "EFI GPT" rather than "Intel/PC partition table" (due to remnants of previous GPT partitioning), so be careful when manually select the correct partition table in the TestDisk prompts. (This probably won't be an issue for most users, but it's worth being aware of.)

I think it's worth trying TestDisk again. I agree the user-interface is very poor, but it's an **extremely** powerful tool. The combination of ddrescue with TestDisk is also extremely powerful, so it's well worth learning how to use effectively. After my near-term Rescuezilla goals are completed, I think a lot of people would benefit from a graphical interface that streamlines the process I have described above! But realistically, it will be a long time before Rescuezilla releases frontends for ddrescue and TestDisk are ready for wide use.

**Let me know how you go!**

**Comment by shasheene** [comment]
TestDisk should be able to do exactly what you want. It is **extremely** powerful, but continues to have an extremely difficult command-line interface until I complete task #102  I should have mentioned TestDisk (and the partclone utility used internally by Rescuezilla) **are not particularly resilient to failing hard drives**.

**For failing hard drives (and optical media), the best tool I have ever used is "ddrescue"**. It is a command-line tool that is extremely robust to the errors caused by dying hard drives, and is able to salvage far more blocks than other tools. ddrescue can be combined with TestDisk for file recovery. The way it works is ddrescue first reads the failing hard drive sequentially and just skips all bad sectors. Then after it the first pass is complete, it goes back and tries the bad sectors in various ways (including reading them backwards) to try and salvage the bad sectors as much as possible. Once the ddrescue backup has completed (which may take a very long time depending on how damaged a hard drive is), you then have a raw backup of your hard drive that you can load into tools like TestDisk.

There is an ddrescue GUI on the internet, but I have never used it. Rescuezilla currently only provides the ddrescue command-line interface.

Here are the step-by-step instructions:

Let's say you're trying to salvage data from a failing 1TB hard drive. You will need a second hard drive with at least 1TB to write the raw, uncompressed disk image that ddrescue creates of the failing hard drive.

1. Open GParted (Start -> Other -> GParted) and use the top-right drop-down menu to identify the device node of your failing hard drive (let's say it was /dev/sdb).
2. Close GParted.
3. Open the File Manager. Mount the _working_ hard drive (with at least eg, 1TB free space). Right-click -> "open current directory in terminal".
4. Run `ddrescue /dev/sdb myFailingHarddrive.ddrescue.img failingHDDLogFile.txt`
  * (Optional: Open a second terminal and run `dmesg -Tw` to better understand where your hard drive damage is located)
5. Wait _many_ hours for the ddrescue command to complete.
6. Run `testdisk myFailingHarddrive.ddrescue.img`. Select the "disk", partition table etc and follow the prompts (see my previous post for detailed instructions)

The above instructions should be sufficient to salvage deleted files from even failing hard drives and optical media.

For completeness, I note that it's definitely possible to mount individual partitions from the ddrescue image (with `fdisk -l myFailingHarddrive.ddrescue.img`, `mount -o loop,offset=XYZ`, and a calculator), and then navigate using a graphical file manager (rather than going through TestDisk). There are [articles](http://www.andremiller.net/content/mounting-hard-disk-image-including-partitions-using-linux) describing how to do this. Though, TestDisk is much more resilient to damaged filesystems than your average file manger.

Side note: It may be possible for TestDisk to incorrectly autodetect a traditional DOS (MBR) drive as a "EFI GPT" rather than "Intel/PC partition table" (due to remnants of previous GPT partitioning), so be careful when manually select the correct partition table in the TestDisk prompts. (This probably won't be an issue for most users, but it's worth being aware of.)

I think it's worth trying TestDisk again. I agree the user-interface is very poor, but it's an **extremely** powerful tool. The combination of ddrescue with TestDisk is also extremely powerful, so it's well worth learning how to use effectively. After my near-term Rescuezilla goals are completed, I think a lot of people would benefit from a graphical interface that streamlines the process I have described above! But realistically, it will be a long time before Rescuezilla releases frontends for ddrescue and TestDisk are ready for wide use.

**Let me know how you go!**

**Comment by shasheene** [comment]
[Rescuezilla v2.0](https://github.com/rescuezilla/rescuezilla/releases/latest) has updated the TestDisk (File Recovery / undelete) and PhotoRec (Photograph deep scan) start menu shortcuts.

The task of making a graphical drop-in replacement to TestDisk is of course captured by task #12. Therefore this GitHub issue can be closed.
