### ISSUE TITLE
Rescuezilla created an organization and repo with our name and logo

### ISSUE THREAD

**Issue by zebradots** [rescuezilla/rescuezilla#116]
Hi @shasheene,

It's come to our attention that you seem to control an organization (https://github.com/redobackup) which is named after and prominently displays our project's logo, likeness, and description. Further, this organization and its repo links direct viewers to a forked project (Rescuezilla) which we do not maintain. This is most certainly misleading for anyone who searches for Redo (or Redo Backup, or Redo Rescue), as your fork is not named "Redo Backup", nor should it be.

As we've already pointed out before, we're delighted you've chosen to fork the legacy Redo 1.0.4 codebase and add so many great features, but as we've detailed in the past at https://sourceforge.net/p/redobackup/discussion/general/thread/d0e37c4750/, the fact that Rescuezilla is a _fork_ of Redo has been all but hidden from users in the past. We've already seen an enormous amount of confusion stem from releases and project announcements made in our name. Fork away, but _please_ use a different name!

We would greatly appreciate it if you would delete the organization `redobackup` named after our project. Redo has published the official legacy source code (https://sourceforge.net/projects/redobackup/) and the newer source code (https://github.com/redorescue/redorescue) under our name. In addition, users searching for "Redo" are, indeed, trying to find our project and source code, and will undoubtedly be confused by links provided by an unaffiliated organization by the same name.

Thank you for your help!

**Comment by shasheene** [comment]
Hi,

Github usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" according to GitHub policies.

The project https://github.com/redobackup/redobackup contains _the_ most accurate _Redo Backup and Recovery_ source code archive ever made, which is very important for software preservation. The project does not merely make the surviving _Redo Backup and Recovery_ source code tarballs available, **but instead constructs an actively useful historical archive as accurately as possible, including the meticulous creation of build automation scripts (`build.sh`) for all available _Redo Backup and Recovery_ versions, painstakingly capturing the host build environment by writing Dockerfiles for all prior versions by comparing the canonical ISO images to what's being built using the `extract_and_checksum_iso.sh` script I made.**

_Redo Backup and Recovery_ is a GPLv3 project, and my work has only been based on the GPLv3 tarballs and other explicitly licensed GPLv3 artifacts (including the ISO image artifacts). 

Based on the Github policies I linked to, I don't believe there is a requirement to remove the _Redo Backup and Recovery_ logo, and tagline description, but regardless of this I have replaced the logo and tagline description.

It's great that you have built _Redo Rescue_  after the last _Redo Backup and Recovery_ v1.0.4 release in 2012, and the 7.5 year gap where the redobackup.org URL you owned had expired and was bought by someone else (not me) through the first-come, first-served nature of domain names.

This Github username situation is very different to the https://alternativeto.net/software/redo-backup-and-recovery/ project where, as part of my Rescuezilla systematic revival project, I requested access (and was granted by that website's administrators) and had the URL updated to https://alternativeto.net/software/rescuezilla/. Even though I was providing a lot of user support on the comment section of that URL (which has now been all deleted, sadly), I was 100% happy to transfer access of that project to you when you resurfaced after 7.5 years even though you were completely unaware of its existence until I mentioned it, because there was pre-existing activity (project votes, reviews and comments) that admittedly was all very relevant to Rescuezilla (as it's a direct source code continuation of _Redo Backup and Recovery_ which was at the time abandoned for 7 years). But the https://github.com/redobackup/redobackup URL has no such pre-existing activity. I registered the username in October 2019 when it was unused, and it fully compiles with Github's [username policies](https://docs.github.com/en/github/site-policy/github-username-policy).

I did the same thing for my revival of LibHand (https://github.com/libhand/libhand) without any issues (though I have to again update the compilation of that project for modern operating systems).

**Whilst you did delete the all my incredibly thorough and painstakingly written _retroactive_ user support that I was systematically providing to the nearly 500 unresolved _Redo Backup and Recovery_ Sourceforge support threads over the past 10 years (even after I spent several hours going back to edit all my comments to link to Redo Rescue in bold text and make it clearer that Rescuezilla is a fork) without giving me advanced notice to at least archive it using the Wayback Machine, that's not relevant here.** Also the fact Rescuezilla implements correct backwards compatibility of backups made with Redo Backup and Recovery, which Redo Rescue does not (this is disputed, see #77) is also not relevant here.

The only thing that is relevant is Github's "[first-come, first-served](https://docs.github.com/en/github/site-policy/github-username-policy)" username policy, from which I don't believe there is any reason to transfer ownership of the 'redobackup' username. My usage of https://github.com/redobackup/redobackup provides a important service from historical archival purposes.

I have seen you already use the https://github.com/redorescue/redorescue URL, and own the redorescue.com URL. My suggestion is you consistently refer to your project as 'Redo Rescue' and 'redorescue'.

**Comment by zebradots** [comment]
Hey @shasheene,

We sincerely hope you understand that **confusion** is the only thing we're trying to prevent. Again, we're very glad you've taken the time to pursue Rescuezilla and will continue to send users your way (there are a lot of great features you have added!), but can you imagine the chaos that would ensue if we were to point users to other projects that bear the same name and logo, but are not affiliated with the Redo authors? Imagine the nightmare of answering support questions for confused users of both projects! That's the nature of the confusion we've seen lately, and what we're trying to avoid for everyone's benefit.

Your comments suggest that you may interpret the GPL license as granting permission to use another entity's name and logo to endorse or suggest sponsorship of an unrelated project. This would be akin to LibreOffice creating an organization called "OpenOffice" that bears the OpenOffice logo to direct users over to LibreOffice. This doesn't happen for obvious reasons, the least of which are any code platform's policies.

By the way, we did provide advance notice about resolving the confusion surrounding posts made on the Redo SourceForge forum under a topic titled "A note regarding Rescuezilla posts on this forum", which can be seen at [this link](https://sourceforge.net/p/redobackup/discussion/general/thread/7b9bbd14e0/). It states, in part and in bold:

> For this reason, we'll soon begin cleaning up some of the posts that are clearly not relevant to supporting or discussing Redo, and wanted to provide ample notice beforehand.

Affected posts were providing support for _Rescuezilla_ releases rather than releases of Redo, and the threads were continuing to lead users of both projects down a confusing path. We hope there are no hard feelings, but everyone can agree the Redo Rescue / Redo Backup forums aren't the best place to host support threads for Rescuezilla.

We really sincerely hope you understand, and aren't upset with us for asking for your help avoiding confusion. We've done nothing to harm Rescuezilla; we're only trying to keep things clean for both projects. If there's anything we can do to help, please don't hesitate to reach out.

**Comment by shasheene** [comment]
I have updated the repository to point to both projects, and updated the logo a second time the Github identicon: https://github.com/redobackup/redobackup

**I think the best solution is to contact Github support and have them decide.** According to the Github Username Policy, usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" so I don't think there's any issue with using that URL for my software preservation work.

As mentioned I have updated the organisation logo and description, but I am still using the name in the Github URL. The GPLv3 license which _Redo Backup and Recovery_ was released **does** allows the use of the name, logo and all assets, as long as the release that's made continues to abide by the terms of the license.

To disallow use of the logo would require releasing the project under a modified GPL license (which it was not). In any event the there is no logo currently being displayed. OpenOffice/LibreOffice is licensed under Apache License 2.0 (among other licenses) which has different provisions to GPLv3, so it's not relevant to this discussion.

Again, **I think the best solution is to contact Github support and have them decide.** Please link them to this discussion. As far as I can tell, according to the Github Username Policy, usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" and since I'm using it for non-trivial software preservation work, I have just as much right to use that URL as anybody else.

**Comment by zebradots** [comment]
Hey @shasheene,

Thanks for reaching out. Not to beat a dead horse, but given your comments, there appears to be some confusion regarding the rights granted by the license under which Redo's source code is distributed. There is a night-and-day difference between the GPL—which is a **copyright** license—and the function and protections afforded a **trademark**, which are to prevent confusion. As one [intellectual property attorney](https://freemius.com/blog/selling-wordpress-plugins-gpl/) explains it:

> However, open-source licenses (including the GPLv2) do not generally extend to trademarks. Trademarks pertain to the manner in which a product (e.g., a plugin, theme, app, etc.) is branded – e.g., the name of the product (**and/or the company from which it originates**), its tagline/slogan, and/or its logo. Thus, while the source code of a project may be freely redistributable under an open source license, such a license does not grant others any rights with respect to the trademarks associated with the project (e.g., the product’s name, the company that developed it, etc.).

(Emphasis ours.) Also:

> As noted, the open source license **does not allow someone to use someone else’s branding** in a commercial context. This is important because **one of the main principles of trademark law is to protect the consumer from confusion as to where a product is coming from**.

Again, emphasis ours. Joomla!, a project which is also released under the GPL, interprets its open source licenses [the same way](https://tm.joomla.org/trademark-faq.html). This makes perfect sense, or else anyone could set up an entity that holds itself out to be Joomla! (identified by the same name and logo), and distribute a fork of the project, which Joomla! would then be expected to provide support and updates for (rather than the new author). Mass confusion.

A repo that simply hosts a project's source code is not a concern. But when an _organization_ is created to identify itself with _another project's trademark_, it could certainly lead to confusion about whether the original author is involved—particularly when the original author is actively providing support for the same project. There can be no question that this ventures straight into the territory of creating "confusion as to where a product is coming from".

Let's be frank. At the end of the day, we have to ask: Why is it necessary to create an organization that carries _our_ name? Wouldn't a `rescuezilla/redobackup` repo suffice? This would alleviate all confusion, as it is prefixed with the _actual_ maintainer's name, rather than ours. What function does the organization provide, given that its only repo is read-only? It isn't to manage development or assign permissions. So if you genuinely want to clean things up, why not transfer the repo to `rescuezilla` and delete the `redobackup` organization? What's so important about maintaining an _organization_ that bears the name of _our_ project?

As we've said in the past, we want to collaborate and enjoy working with you. You've done a lot of great work and are set to do much more. Hopefully this request doesn't come across as anything but friendly and reasonable. We haven't done anything unscrupulous. Neither have we created an organization named "Rescuezilla"—and can't possibly see the justification for doing so. We simply want to avoid confusion among our users, as we've dealt with enough already.

Is this request unreasonable?

**Comment by shasheene** [comment]
OK, I still think Github would side with first-come first-serve principle, since Redo Backup is not a registered trademark, but you have convinced me. I will be transferring the repository to you immediately.

I am also clearing out the discussion in this github issue. Then we can move forward. Stand by.

**Comment by shasheene** [comment]
Hi @zebradots,

I have moved the https://github.com/redobackup/redobackup repository (which contains _the_ most accurate _Redo Backup and Recovery_ source code archive ever made, see below) to https://github.com/rescuezilla/redobackup and deleted the https://github.com/redobackup organization.

**The https://github.com/redobackup URL is all yours.**

I am returning this **_despite_** the fact that Github usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" and fully complies with the Github Policy (additionally all assets are complying with the GPLv3 license) and I was under no obligation to transfer ownership.

As we earlier discussed, I initially wanted to escalate this to Github support  and have them make a decision. "redobackup" is not a registered trademark, so I think the Github Username Policy would have sided with me and I could keep the org to host my meticulously reconstructed _Redo Backup and Recovery_ source code archive (far more than merely extracting tarballs) and preserve the fact "fork of" link to Rescuezilla.

However, I have decided in the spirit of the free and open-source software movement to delete the redobackup organization and allow you to register it.

**Comment by shasheene** [comment]
Hi @zebradots,

I have moved the https://github.com/redobackup/redobackup repository (which contains _the_ most accurate _Redo Backup and Recovery_ source code archive ever made, see below) to https://github.com/rescuezilla/redobackup and deleted the https://github.com/redobackup organization.

**The https://github.com/redobackup URL is all yours.**

I am returning this **_despite_** the fact that Github usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" and fully complies with the Github Policy (additionally all assets are complying with the GPLv3 license) and I was under no obligation to transfer ownership.

As we earlier discussed, I initially wanted to escalate this to Github support  and have them make a decision. "redobackup" is not a registered trademark, and I am confident the Github Username Policy would have sided with me and allow me to keep the org to host my meticulously reconstructed _Redo Backup and Recovery_ source code archive (far more than merely extracting tarballs) and preserve the now-lost fork linkage based on the first-come, first-serve policy.

However, I have decided in the spirit of the free and open-source software movement to delete the redobackup organization and allow you to register it.

**Comment by shasheene** [comment]
Hi @zebradots,

I have moved the https://github.com/redobackup/redobackup repository (which contains _the_ most accurate _Redo Backup and Recovery_ source code archive ever made, see below) to https://github.com/rescuezilla/redobackup and deleted the https://github.com/redobackup organization.

**The https://github.com/redobackup URL is all yours.**

I am returning this **_despite_** the fact that Github usernames are provided on a "[first-come, first-served basis](https://docs.github.com/en/github/site-policy/github-username-policy)" and fully complies with the Github Policy (additionally all assets are complying with the GPLv3 license) and I was under no obligation to transfer ownership.

As we earlier discussed, I initially wanted to escalate this to Github support  and have them make a decision. "redobackup" is not a registered trademark, and I am confident the Github Username Policy would have sided with me based on the first-come, first-served policy, which would allow me to keep the org to host my meticulously reconstructed _Redo Backup and Recovery_ source code archive (far more than merely extracting tarballs) and preserve the now-lost prominent fork linkage.

However, I have decided in the spirit of the free and open-source software movement to delete the redobackup organization and allow you to register it.

**Comment by zebradots** [comment]
Hi @shasheene,

Thank you for your understanding and for helping find a solution to avoid any confusion for those searching for Redo. We hope you'll agree that the README.md at https://github.com/redobackup/redobackup provides a clear and official explanation from the project's authors about Redo's origins, and does a fair job of promoting Rescuezilla in the process.

If our description of Rescuezilla or its repo for previous Redo releases is inaccurate in any way, please let us know. We sincerely want to bring visibility to your project for reasons we've outlined in the past. This benefits everyone involved. Thanks again for all you've done to get things cleaned up.

**Comment by shasheene** [comment]
Yep, looks good. Nice job!
