### ISSUE TITLE
backup to NFS

### ISSUE THREAD

**Issue by chicks-net** [rescuezilla/rescuezilla#118]
Howdy Shasheen,

I've enjoyed using your product so far.  I'm see you have lots of plans already, but I'm wondering: have you considered making it possible to backup to an NFS drive?  Some folks have NAS drives or other Linux systems that do not have SMB/CIFS enabled.  I also have worked in environments with large redundant NFS infrastructure and no concern for Windows protocols.  Being able to work with NFS would be great in these situations.  What are do you think?

**Comment by shasheene** [comment]
Great job adding NFS support to _Redo Rescue_, @zebradots! I am not offended if many users (@chicks-net included) prefer to use _Redo Rescue_.

I should mention the November 2019 Rescuezilla fork/revival of _Redo Backup and Recovery_ has very different goals and methodology compared to the June 2020 _Redo Rescue_ project. Rescuezilla's primary goal is Clonezilla compatibility, after having first [unified and stabilized the numerous previous _Redo Backup and Recovery_ versions](https://github.com/rescuezilla/rescuezilla/wiki/Bugs-in-unofficial-Redo-Backup-updates) that were been causing some users a lot of grief (only increased due to the unique history of _Redo Backup and Recovery_).

**Overtime, I see Rescuezilla and _Redo Rescue_ increasingly diverging.** Right now, both frontends are based on the same _Redo Backup and Recovery_ wizard design, so of course they will have very similar workflow. Overtime, I will be developing data salvage functionality based on [`ddrescue`, `testdisk`, `extundelete`](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Project-Roadmap). Even if @zebradots/_Redo Rescue_ chooses to pursue these features, I am sure the workflow we design will be very different.

Also @zebradots, _Redo Rescue_ apparently does not yet support booting on EFI-only machines. As per the GPLv3 license, you are encouraged to copy and paste Rescuezilla's [painstakingly researched support for EFI/Secure Boot](https://github.com/rescuezilla/rescuezilla/blob/master/build.sh) to benefit users of _Redo Rescue_.

I am definitely keen to avoid NIH ("Not Invented Here") Syndrome, where great implementations are re-invented poorly. So where it makes sense, I am happy to include third-party applications (eg, GParted) and potentially applications designed by _Redo Rescue_ (and I encourage @zebradots to consider doing the same).

**Comment by shasheene** [comment]
Great job adding NFS support to _Redo Rescue_, @zebradots! I am not offended if many users (@chicks-net included) prefer to use _Redo Rescue_.

I should mention the November 2019 Rescuezilla fork/revival of _Redo Backup and Recovery_ has very different goals and methodology compared to the June 2020 _Redo Rescue_ project. Rescuezilla's primary goal is Clonezilla compatibility, after having first [unified and stabilized the numerous previous _Redo Backup and Recovery_ versions](https://github.com/rescuezilla/rescuezilla/wiki/Bugs-in-unofficial-Redo-Backup-updates) that were been causing some users a lot of grief (only increased due to the unique history of _Redo Backup and Recovery_).

**Overtime, I see Rescuezilla and _Redo Rescue_ increasingly diverging.** Right now, both frontends are based on the same _Redo Backup and Recovery_ wizard design, so of course they will have very similar workflow. Overtime, [I will be developing data salvage functionality based on `ddrescue`, `testdisk`, `extundelete`](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Project-Roadmap). Even if @zebradots / _Redo Rescue_ chooses to pursue these features, I am sure the workflow we design will be very different.

Also @zebradots, _Redo Rescue_ apparently does not yet support booting on EFI-only machines. As per the GPLv3 license, you are encouraged to copy and paste Rescuezilla's [painstakingly researched support for EFI/Secure Boot](https://github.com/rescuezilla/rescuezilla/blob/master/build.sh) to benefit users of _Redo Rescue_.

I am definitely keen to avoid NIH ("Not Invented Here") Syndrome, where great implementations are re-invented poorly. So where it makes sense, I am happy to include third-party applications (eg, GParted) and potentially applications designed by _Redo Rescue_ (and I encourage @zebradots to consider doing the same).

**Comment by shasheene** [comment]
Great job adding NFS support to _Redo Rescue_, @zebradots! I am not offended if many users (@chicks-net included) prefer to use _Redo Rescue_.

I should mention the November 2019 Rescuezilla fork/revival of _Redo Backup and Recovery_ has very different goals and methodology compared to the June 2020 _Redo Rescue_ project. Rescuezilla's primary goal is Clonezilla compatibility, after having first [unified and stabilized the numerous previous _Redo Backup and Recovery_ versions](https://github.com/rescuezilla/rescuezilla/wiki/Bugs-in-unofficial-Redo-Backup-updates) that were causing some users a lot of grief (only increased due to the unique history of _Redo Backup and Recovery_).

**Overtime, I see Rescuezilla and _Redo Rescue_ increasingly diverging.** Right now, both frontends are based on the same _Redo Backup and Recovery_ wizard design, so of course they will have very similar workflow. Overtime, [I will be developing data salvage functionality based on `ddrescue`, `testdisk`, `extundelete`](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Project-Roadmap). Even if @zebradots / _Redo Rescue_ chooses to pursue these features, I am sure the workflow we design will be very different.

Also @zebradots, _Redo Rescue_ apparently does not yet support booting on EFI-only machines. As per the GPLv3 license, you are encouraged to copy and paste Rescuezilla's [painstakingly researched support for EFI/Secure Boot](https://github.com/rescuezilla/rescuezilla/blob/master/build.sh) to benefit users of _Redo Rescue_.

I am definitely keen to avoid NIH ("Not Invented Here") Syndrome, where great implementations are re-invented poorly. So where it makes sense, I am happy to include third-party applications (eg, GParted) and potentially applications designed by _Redo Rescue_ (and I encourage @zebradots to consider doing the same).

**Comment by zebradots** [comment]
Thanks @shasheene! Briefly (so as not to hijack this issue thread), we agree that this divergence means more options for users, and that's a good thing. Redo's philosophy strongly resists feature creep in favor of simplicity. We aren't opposed to adding a Debian-packaged file recovery tool, for example, but have no intention of developing a GUI for them. We certainly appreciate the offer to reuse your hard work on UEFI boot. (Congratulations on a job well done!) We did take a peek at Rescuezilla's approach to adding UEFI support a while back, but Debian-specific quirks led us to a different recipe. UEFI support is [slated for inclusion](https://github.com/redorescue/redorescue/issues/18), but it won't be happening for a while!

**Comment by shasheene** [comment]
Sounds good! Your input is fully relevant to users interested in NFS support, I don't mind the topic hijacks because it's great to understand the _Redo Rescue_ roadmap a little bit better.

Your philosophy around resisting feature creep is definitely a good thing. The goals and methodologies of Clonezilla, Rescuezilla and _Redo Rescue_ differ greatly so it's great that users have more options.

I hope to continue to keep the Rescuezilla user-interface simple, but the Rescuezilla internals will definitely have **WAY** broader scope compared to _Redo Rescue_ (not least because of the mid-October 2020 support for the very complex Clonezilla image format).

**Comment by shasheene** [comment]
@chicks-net NFS support now available in the **[latest version of Rescuezilla](https://github.com/rescuezilla/rescuezilla/releases/latest)**.

**Comment by chicks-net** [comment]
> @chicks-net NFS support now available in the **[latest version of Rescuezilla](https://github.com/rescuezilla/rescuezilla/releases/latest)**.

Thank you so much!  I will test this soon.  :smiley: 

You landed a bunch of stuff in this release. :guitar:  Kudos.
