### ISSUE TITLE
Weighting progress bar by partition size (in bytes) not number of partitions

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#129]
If I'm restoring 4 parts in a window restore. 95% of the data (and as a result time) are in the last part. It would be nice if there were 4 loading bars so I don't get a false sense of it being almost done when its at 75% but only 5% of the entire restoration process is done. I'm just used to glancing over at the progress instead of looking below it for the true result.

**Comment by shasheene** [comment]
Thanks for raising this.

You are correct, Rescuezilla v2.0 (which rewrote the entire application in the Python programming language) has loading bar that is based on the _number_ of partitions but does not yet take into account the size of the partitions.

Rescuezilla v1.0.6.1 had a progress bar that was correctly weighted by partition size (in bytes), producing a linear loading bar where having small partitions don't give a false sense of progress.

I hope to returning to weighting the progress by the partition size in bytes in the coming weeks.

**Comment by shasheene** [comment]
For completeness I note that a user named bob on the Sourceforge forum [recently](https://sourceforge.net/p/rescuezilla/discussion/support/thread/1b97c33a66/) had the same issue:

> This may be obvious to most people, but not me. So, I'm hoping someone can assist.
On the Rescuezilla screen titled "Step 7: Creating Backup Image" there is a blue status bar that isn't labeled. Then, lower on the screen is a line of text explaining the current status (Elapsed, Remaining, Completed %, GB/min). My question is I don't understand what the blue status bar means since it isn't labeled and it never corresponds to the status reflected in the status text line. I've come to ignore it since the text status has the info I need, but I'd like to understand what it means..

I replied:

> The blue progress bar is based on the *number* of partitions but does not currently take into account the *size* of the partitions. For Rescuezilla v2.2 I will be weighting the progress bar by the partition size in bytes, which will produce correct proportions **so making backups of many small partitions won't give a false sense of overall progress**.
