### ISSUE TITLE
Translation of Rescuezilla into Polish

### ISSUE THREAD

**Issue by zeit439** [rescuezilla/rescuezilla#135]
Congratulations on a great program.
I made the whole translation into Polish from three files ordered on the website.
Best regards.
[de.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5539182/de.ko.txt)
[graphical-shutdown.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5539187/graphical-shutdown.ko.txt)
[rescuezilla.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5539189/rescuezilla.ko.txt)

**Comment by shasheene** [comment]
Hi zeit439,

Thanks for the translation! **I have selected the standard Polish keyboard layout for your translation. Let me know if this is not sufficient.**

Your translation will be included in Rescuezilla v2.1 (which due to growing scope is still a few weeks away from being released).

I should mention Rescuezilla v2.1 is adding a 'Verification' mode to verify backup images are restorable, and an ['Image Explorer' mode](https://github.com/rescuezilla/rescuezilla/issues/20#issuecomment-726565808) to mount and explore backup images. Also in the future I will add [cloning / device-to-device mode](https://github.com/rescuezilla/rescuezilla/issues/47):

<a href="https://user-images.githubusercontent.com/1414379/99139006-fe5d5480-2684-11eb-89a7-777c009d97a3.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/99139006-fe5d5480-2684-11eb-89a7-777c009d97a3.png"></a> 

It probably makes the most sense to release these additional modes only in English at first. After users of Rescuezilla have provided their feedback it can be translated into other languages.

**Comment by shasheene** [comment]
Translation now available in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest):

<a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/grub.png><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/grub.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/welcome.png><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/welcome.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/restore.step2.png><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/restore.step2.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/restore.step4.not.overwrite.png><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pl/restore.step4.not.overwrite.png"></a>
