### ISSUE TITLE
Ability to add description to images

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#137]
It would be kind of nice to elaborate in more detail besides just the name of the image itself. Such as if you have multiple images but different setups without having to worry about making your own syntax. Preferably connecting it to just a .txt file in the same directory so it could more easily be edited.

**Comment by shasheene** [comment]
I agree that would be good.

Ideally Rescuezilla would provide a field to enter this, but even just being able to create file a file (let's call it "description.txt") using Notepad.exe in the image folder, and having this displayed in Rescuezilla's table would still be really good.

I don't believe Clonezilla supports anything similar. **Adding "description.txt" file would constitute extending Clonezilla's image format**. I am sure it won't introduce an incompatibilities at this moment, but **I am very hesitant to introduce any extensions to the format without consulting with Clonezilla author Steven Shiau.

**@stevenshiau, do you have any qualms around Rescuezilla adding a description file to the Clonezilla image folder?** Clonezilla users may ask for Clonezilla to display this file, so the designs decisions around this will eventually affect you.

**Comment by AE720** [comment]
Thank you for your descriptive response to a small request and I fully understand wanting to be safer than sorry. This might also tie into the idea of having a file that "caches" the images so loading is faster. It can tell you where images are and if found, to quickly gloss them over and it becomes a "delta scan" of sorts. That same idea might also be to house the description too.

**Comment by stevenshiau** [comment]
@shasheene As you know, the image format for Clonezilla is a directory, hence you can add any extension files you want. Since Clonezilla live uses TUI, it's not easy to display too much info. For the moment we do not use the plain text file like "description.txt" in the image dir. I suggest if you want to add your extension, maybe have a prefix, make it like: RZ-description.txt.

**Comment by shasheene** [comment]
> I suggest if you want to add your extension, maybe have a prefix, make it like: RZ-description.txt

@stevenshiau, this is _exactly_ the kind of input I was hoping for! Thanks!

By the way, you might want to unsubscribe to notifications on this GitHub issue (if you haven't already). Otherwise as I complete this task, GitHub will send you a lot of spam emails and notifications that will be unrelated to Clonezilla.

**In the coming weeks/months/years, feel free to tag me on any discussion that you believe Rescuezilla could benefit from.**
