### ISSUE TITLE
NVMe M2 drive not detected

### ISSUE THREAD

**Issue by RobertHulsebos** [rescuezilla/rescuezilla#138]
I have a Dell XPS8910 desktop with Windows 10 installed on a NVMe M2 256 GB SSD. Rescuezilla does not detect this drive. 
When I open a terminal window and  issue 'fdisk -l' command, then the drive is not listed. Missing driver?
![Liteon drive](https://user-images.githubusercontent.com/73020730/99877018-6e2a8c80-2bfb-11eb-8e25-a9997ce33f51.jpg)

**Comment by RobertHulsebos** [comment]
This is how Windows 10 sees the drive, the missing drive is Drive 1. All other drives are recognized and supported.
![Liteon drive2](https://user-images.githubusercontent.com/73020730/99877074-e2fdc680-2bfb-11eb-9d6e-07e4c04508db.jpg)

**Comment by shasheene** [comment]
Hi Robert,

Just to confirm, are you using the latest version of Rescuezilla (currently v2.0)?

As you know, if running `fdisk -l` or opening GParted Partition Editor doesn't display your NVMe disk then the Rescuezilla frontend definitely will not.

Dell XPS8910 looks like it's from around the year 2016/2017 with 6th generation Intel Core processors and eg, GeForce GTX 750 graphics. **I would have expected Rescuezilla v2.0 (which is based on Ubuntu 20.04) to have extremely good hardware support for 3-4 year old hardware.**

**Comment by RobertHulsebos** [comment]
Yes, I am using v2.0. See also attached pictures. Indeed, my Dell dates from 2016, so you're correct. I would have expected the same thing...  I noticed the disk checking on startup of Rescuezilla - is this normal?
![IMG_20201121_174751](https://user-images.githubusercontent.com/73020730/99882658-70eca800-2c22-11eb-934a-658b5cfd4c62.jpg)
![IMG_20201121_174106](https://user-images.githubusercontent.com/73020730/99882662-74802f00-2c22-11eb-8b12-645ed14e188e.jpg)

**Comment by RobertHulsebos** [comment]
As for GParted, here are some pictures that may perhaps help... The /sda drive is the (real) harddrive of the Dell, /sdb is my USB backup drive, /sdc is the USB drive that I booted from and holds Rescuezilla. The SSD drive that holds Windows 10 is missing here, just like with 'fdisk'.
![IMG_20201121_174302](https://user-images.githubusercontent.com/73020730/99882692-ab564500-2c22-11eb-84b9-7e5622ccf018.jpg)
![IMG_20201121_174233](https://user-images.githubusercontent.com/73020730/99882704-bad58e00-2c22-11eb-902c-4b80c72d74eb.jpg)

**Comment by RobertHulsebos** [comment]
One other thing I noticed during Rescuezilla startup is these messages: (see picture) Looks like they are some kind of error messages. Could they be related?
![IMG_20201121_174644](https://user-images.githubusercontent.com/73020730/99882796-55ce6800-2c23-11eb-997a-e48ce66cf2ef.jpg)

**Comment by shasheene** [comment]
Thanks for the detailed message. I'm not sure if that kernel error message is related.

**Most likely you're missing firmware**. Run `dmesg -Tw` and look through the results and try to find if there's any firmware load errors.

By the way I should mention for another GitHub issue I created a test build of Rescuezilla based on Ubuntu 20.10 (Groovy) (October 2020 release):

> **I have created a test build of Rescuezilla v2.0 on Ubuntu 20.10 (Groovy), rather than Ubuntu 20.04 (Focal). Please download it and check if your problematic machines boot: [rescuezilla.amd64.groovy-test-1.2020-10-29.iso](https://drive.google.com/file/d/1FX-nsMtSY_8h9l6-Ski8AamYdIoceQRH/view?usp=sharing)**
> 
> The only relevant change is using a newer Linux kernel version 5.8.0-26, rather than Linux kernel version 5.4.0-51 that was used in Rescuezilla v2.0.

It might be worth trying this build because the newer Linux kernel may come with useful bug fixes. **Please don't use this Groovy test version beyond testing the whether the NVMe SSD is detected by the new Linux kernel**: upgrading the operating system often makes many internal changes, and **I have not yet done thorough testing**, I am just suggesting this build to confirm whether Ubuntu 20.10 (Groovy) would solve this hardware detection issue.

**Comment by RobertHulsebos** [comment]
I tried the Groovy ISO, but still no NVMe SSD drive from Liteon. Attached the output of 'dmesg -Tw' command. There is one line mentioning a remapped NVMe device and suggesting BIOS setup change. But no mentioning of Liteon SSD anywere...
[dmesg1.txt](https://github.com/rescuezilla/rescuezilla/files/5579953/dmesg1.txt)

**Comment by RobertHulsebos** [comment]
I found this on the internet: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1694596 
I have exactly this drive. I checked with Dell support, it contains the latest firmware.
I have no problems with this drive, it is working fine with Windows 10...

At the bug report mentioned above states at the end: 

    **Changed in linux (Ubuntu):
    status: | Confirmed → Won't Fix**

So does this mean support for this Liteon drive is canceled?

**Comment by RobertHulsebos** [comment]
See https://bbs.archlinux.org/viewtopic.php?id=204629 and https://www.dell.com/support/article/nl-nl/sln299303/loading-ubuntu-on-systems-using-pcie-m2-drives?lang=en 
I tried to set SATA from RAID ON to AHCI in BIOS, as suggested in above articles, but it did not help. More over, with this BIOS setting my system was not able to boot Windows 10 anymore, so I had to revert it.

**Comment by shasheene** [comment]
**The last Dell XPS 8910 System BIOS update was 18 March 2019. It's definitely worth updating to the latest BIOS update because there may be some bug fixes which improve things.** Dell doesn't make the release notes very clear so I'm not sure.

I don't have any insights to provide you on why your CX2-8B256 NVMe drive doesn't work with Ubuntu, but I did come across: https://superuser.com/a/1030293/1160880

I don't know exactly the options you have in the BIOS, but I recommend switching temporarily from RAID ON to 'disabled' in the BIOS if possible (as it sounds like you already tried), _and_ temporarily switching from 'UEFI' boot to some kind of 'BIOS/CSM' boot option as suggested by another of the answers on that SuperUser link. As you have said, these two things will definitely prevent your Windows 10 from booting until they are switched back to the original.

Also during that same attempt, it's probably worth pressing tab in the Rescuezilla menu (after selecting 'English' and highlighting the 'Start Rescuezilla' item) and replacing the `quiet splash` boot options with `nvme_load=YES` then press F10 as per the Dell instructions that you've linked to. I don't know if that kernel option will have any effect on the Linux kernel in Rescuezilla but it can't hurt to try.

It's probably worthwhile trying all of the above in one go. Let me know how you go!

**Comment by shasheene** [comment]
By the way I was wrong when I said the latest bios for your machine was from March 2019. The latest BIOS appears to be v1.1.12 from 17 August 2020: https://www.dell.com/support/home/en-au/product-support/product/xps-8910-desktop/drivers

As mentioned I don't know the exact changes, but it's definitely worth upgrading the BIOS first.

**Comment by RobertHulsebos** [comment]
I updated the BIOS. The SSD firmware was already updated before. It didn't help. It tried switching the BIOS SATA option away from RAID ON to AHCI  (no other option) but this prevents Windows 10 from booting. It causes it to crash somewhere in the startup phase and effectively creating a reboot loop. After a number of times Dell recovery software kicks in and asks to restore original software. I really have to abort things there, to avoid my Windows 10 + installed apps being overwritten...  
Unless you have any other ideas, I give up now. I guess Linux just does not support it and I will have to revert to some other backup tool on Windows for backing up this partition...  sorry...  ;-(

**Comment by shasheene** [comment]
Sad to hear there are no other storage mode/options in the BIOS to make the NVMe device detectable. If you have any other NVMe drives available it might be worth substituting it into this machine. I appreciate your time is precious and you may not have any interest in troubleshooting this issue.

By the way, I forgot to mention earlier: **You may be interested in trying "Hiren’s BootCD PE". It has several popular hard drive imaging tools (AOMEI Backupper, Acronis TrueImage, Macrium Reflect) on a Windows-based environment.**

**Comment by RobertHulsebos** [comment]
Thanks for your support, I am not gonna replace the LiteOn SSD drive. Also I just want to make a backup, not to reinstall the OS and apps. It's a pity Linux can't support this drive like it is standard on Dell, but I guess my best option now is to revert to Windows based solution. The issue has already taken me more time than I anticipated. 
Hiren's BootCD -> Thanks for your suggestion - I will try this and see if it works for my SSD..

**Comment by shasheene** [comment]
Sounds good. Feel free to let me know your experience with Hiren's BootCD in a sentence or two below once you've had a chance to try it out.

I'm going to close this GitHub issue and change the title.

**Comment by RobertHulsebos** [comment]
Today I found that there is a way to convert from RAID to AHCI without having to re-install Windows 10. The procedure is actually not to difficult and works with my PC. After converting Rescuezilla recognizes the NVMe disk. Hurrah! 
Here is the procedure:

1. Run msconfig
2. Enable Safe Boot (minimal)
3, Reboot into BIOS and change SATA setting from RAID to AHCI
4. Boot up (will be into safe mode)
5. Run msconfig again and disable Safe Boot.
6. Reboot

This took me 5 minutes and worked without a flaw,

**Comment by shasheene** [comment]
Very nice, glad to hear you have found a solution, @RobertHulsebos!

**Comment by RobertHulsebos** [comment]
Yes. I am glad. I can now use Rescuezilla on all Dell PCs. No more exceptions. Hopefully, this helps other users with same problem too...

**Comment by ahmad-sm02** [comment]
I had the same issue and I’m please to say that changing the SATA mode from RAID to AHCI made the drive show in rescuezilla. Thank you!
