### ISSUE TITLE
Write Speed to Slow / No write permission on mounted drives

### ISSUE THREAD

**Issue by mrtootoo** [rescuezilla/rescuezilla#15]
I was happy to see ReDo come to life again.  I tried v1.05 for the first time today and had a few concerns.  I burned ISO to a CD to make backup.  The GUI seemed very much like v.104.  The simplicity is why I prefer ReDo over Clonzilla.  However, my issues were as follows:

1.  The backup took too long.  My 256GB SSD has less then 100GB of data.  The back up took over 2.5 hours.  With v1.04, this back up takes about 6 minutes.  The write speed started over 3GB/sec and reduced to little over 100MBs.  The size of the back up was 8.1GB, on v1.04 the same backup was 6.8GB.

2.  Once the backup was complete, although my drives were mounted, I did not have permission to access my drives.  With v.104 I typically move my backup directory after completion of the back up process.

I have not tested restoration yet (don’t want to wait two hours).  I did save my logs if needed.  Looking forward to v1.06.  Please let me know if there is a better way or place to leave feedback.  Thanks.

**Comment by shasheene** [comment]
Thank you for the report. For now, this is a reasonable place to leave feedback. Please do upload the log files if you have them!

1. In testing of both _Redo Backup and Recovery_ v1.0.4 and Rescuezilla v1.0.5 using a 250GB SSD on a very old Core 2 Duo machine backing up and restoring partitions take a similar time frame of several hours. I will look further into whether any changes to partclone over the past 7 years have slowed down the backup process.

2. Rescuezilla v1.0.5 no longer runs the file manager as root. The logic was there is a big risk of a user accidentally deleting their own backup, or a critical system file. Perhaps the safest approach is to improve the Rescuezilla's destination directory selection to make it not necessary to manually move the backup directory.

**Comment by shasheene** [comment]
Also, if you have a spare USB thumb drive, it's highly recommended you use balenaEtcher to flash the Rescuezilla ISO image onto it (this deletes everything on the USB thumb drive).

Booting from USB thumb drive is _much_ faster than booting from a CD!

**Comment by mrtootoo** [comment]
1) I believe Clonezilla uses Partclone as well, back ups takes less than 10 minutes on the same drive using Clonzilla.
2) If root is not provided by default, how does one obtain root?  Having root privileges could be useful.
3) Agree, booting from USB is preferred over CD.  I was simply comparing Clonezilla and v1.04 using the same media.
4) Log files attached.
5) Thanks again for reviving ReDo/Rescuezilla
[Logs.zip](https://github.com/rescuezilla/rescuezilla/files/3826911/Logs.zip)

**Comment by shasheene** [comment]
1a. The backup code is still using gzip, instead of the multi-threaded drop-in replacement pigz (which is used elsewhere in Rescuezilla v1.0.5). Clonezilla uses pigz. Assuming the CPU is the bottleneck of your backup (I haven't confirmed that), if you have 4 cores you can expect pigz to provide close to a 4 times speedup. This does not explain why Redo Backup v1.0.4 (which uses gzip) was very fast.
1b. Are you using Clonezilla AMD64 or i386? There is likely a big speedup by pigz/partclone using fast vector instructions which Rescuezilla v1.0.5 cannot take advantage as it's i386 (will fix in #3). This also does not explain why the i386 application Redo Backup v1.0.4 was very fast.
2. The login session runs under the 'ubuntu' live user, but every application that needs root has been configured using a PolicyKit file. A root terminal can be opened by double-clicking the terminal on the desktop, and then the file manager can be launched by typing 'pcmanfm'.

Thank you for the logs. I will try and reproduce your issue on my system.

**Comment by mrtootoo** [comment]
V1.05.1 milestone is great news!  Thanks.  BTW...I did try again with a USB 3.1 thumb card.  Results were the same.

**Comment by shasheene** [comment]
I am approaching the release of v1.0.5.1. I want to make progress on this issue, so I will be taking measurements of backup/restore speeds using Redo Backup v1.0.4, Rescuezilla v1.0.5.1 and Clonezilla Live 2.6.4-10 (AMD64) against some test environments. My aim is to understand the bottlenecks and reasons behind the speed difference.

Depending on the outcome of my analysis, any changes made to the speed of Rescuezilla will likely be in the release _after_ v1.0.5.1 unfortunately.

**Comment by shasheene** [comment]
@mrtootoo, to help me look into this issue further, can you launch the version of Redo that you use, then open a terminal and run the command `uname -r`?

Please post the output, it will help me figure out if you are using an unofficial update of Redo which reports itself as v1.0.4 but actually is a different version.

**Comment by mrtootoo** [comment]
I will be able to check for you later tonight or tomorrow.  But I can tell you I was using 1.04 than moved on to "redo_1204.5_20160223.iso" which can be found at "https://drive.google.com/drive/folders/0B36hIlLlK--hRzRUbHdzZXMyVTQ".  It was written by [OAM775](https://sourceforge.net/u/oam775/profile/)  His thread is [here](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d469c53d/)

**Comment by shasheene** [comment]
OK, the fact you're using redo_1204.5_20160223.iso is the information I was looking for.

Was this the release that you backed up 100GB of data from your 256GB SSD in less than 6 minutes? Or did you see it on the original v1.0.4?

**Comment by mrtootoo** [comment]
I had similar results with both versions.  I also have similar results with Clonezilla.  One clarification, I looked at my drive, it contains only 25GB of data, not 100GB.

uname -r
3.13.0-79-generic

**Comment by mrtootoo** [comment]
>     2\. Perhaps the safest approach is to improve the Rescuezilla's destination directory selection to make it not necessary to manually move the backup directory.

The reason I move the backup file is I found 1.04 to work best saving to the root directory.  It does not save or restore from a few directories deep.  I never did try with 1.05.

**Comment by mrtootoo** [comment]
> Depending on the outcome of my analysis, any changes made to the speed of Rescuezilla will likely be in the release _after_ v1.0.5.1 unfortunately.

Well I tried anyway.  I think it was even slower with 1.05.1.  My 250GB drive had 36GB of data and only one partition.  The backup started fine at 6GB/s with an estimated completion time of 7 minutes.  After 53 minutes, only 30% was complete and write speed was 219MB/s.  Clonezilla and ReDo 1.04 still complete the task in under 7 minutes.
One other thing I noticed, with version 1.04, there was a check of the partition before the saving of the partition.  I did not see that with 1.05.1.  (maybe I just missed it)

**Comment by shasheene** [comment]
@mrtootoo,

You're using a machine with more than 16GB of RAM correct? You'll be happy to learn that I have tracked down the source of the slow transfer speed. It's a bug in the [Linux memory allocator on 32-bit versions of Linux](https://bugzilla.kernel.org/show_bug.cgi?id=196157).

The next Rescuezilla won't exhibit this issue, but **for now you can speedup Rescuezilla v1.0.5.1 by pressing 'tab' at the boot menu and modifying the line that pops up so it ends in "quiet mem=10G splash --" instead of "quiet splash --". Then press enter** and after it finishes booting do your backup/restore operations as normal. The "mem=10G" option tells Linux that there is only 10GB of memory installed in your system (instead of your actual amount which will likely be 16GB or greater), which prevents the bug from being triggered.

As mentioned, the next version of Rescuezilla will not exhibit this issue. For v1.0.5.1, please try the workaround and tell me your results.

**Comment by mrtootoo** [comment]
> **pressing 'tab' at the boot menu and modifying the line that pops up so it ends in "quiet mem=10G splash --" instead of "quiet splash --". Then press enter**

That fixed it!  A 250GB drive with 24GB of data was saved in 4.7 minutes.  That is faster than 1.04 and Clonezilla.  Not important, but I also noticed I no longer had the notification of write speed as before (GB/sec).  I assume that has something to do with the boot menu modification.

**Comment by mrtootoo** [comment]
>     2\. Rescuezilla v1.0.5 no longer runs the file manager as root. The logic was there is a big risk of a user accidentally deleting their own backup, or a critical system file. Perhaps the safest approach is to improve the Rescuezilla's destination directory selection to make it not necessary to manually move the backup directory.

So I did try saving the back up directly to the directory I store my backups, third directory from root.  Like v1.04, this is not possible.  Not a major issue, but that is why I was moving my backup file prior to exiting ReDo.

**Comment by shasheene** [comment]
@mrtootoo,

I have almost certainly tracked down your second issue. You are using a path which contains a quote character (or other special characters), correct?

I have been testing paths containing space characters and nested directories without issue, but until now didn't try special character types until now. Next release will better support special characters in paths. You are very likely not the only person to have this issue. Especially since this issue effects every versions of Redo Backup and Rescuezilla until now.

**Comment by mrtootoo** [comment]
I do have a hyphen in the path's name.

**Comment by shasheene** [comment]
@mrtootoo 

The two issues you have described here should be fixed by Rescuezilla v1.0.6, which [has just been released](https://github.com/rescuezilla/rescuezilla/releases/latest).

Use the 64-bit version to avoid the slowdown issue, and you should be able to save the backup in a subdirectory any legal path (rather  than being limited with what names to give a backup). I could be wrong, but I think this removes most of the need to move around files after the backup is made.

I am happy to discuss the permission to move around files issue more if what is in Rescuezilla  v1.0.6 is not sufficient. By the way if you open and close GParted after using Rescuezilla it refreshes the file manager volume listings -- this might be useful for you (I will make a future version of Rescuezilla do that automatically).

Let me know if you have any issues.

**Comment by mrtootoo** [comment]
Thanks.  I did make a back up with 1.0.6, saved to a directory multi levels deep; back up was saved within 5 minutes.  I currently have no need for elevated permissions.
