### ISSUE TITLE
Improve usability on low-resolution displays: 640x480, 800x600, 1366x768

### ISSUE THREAD

**Issue by candrapersada** [rescuezilla/rescuezilla#164]
why the panel covers the next button? 1366x768
![IMG20210102043100](https://user-images.githubusercontent.com/36833664/103447665-ac1dd480-4cc0-11eb-8e06-f9716a929266.jpg)

**Comment by shasheene** [comment]
**If you have a display with higher resolution, you can modify the screen resolution. You can do this by either clicking the desktop icon "ARandR" (or right-clicking the desktop wallpaper and selecting "Display resolution and layout"). Then you can use arandr's imperfect interface to select a higher resolution and apply the changes.**

The minimum resolution requirements of Rescuezilla is I believe about 1200x800. On many lower-end laptops, the maximum resolution is 1366x768, which doesn't have enough vertical pixels. I hope to optimize Rescuezilla to run on much lower resolutions because 800x600 and even 640x480 are resolutions that even high-end computers may be forced to use, especially when using the generic VESA graphics drivers that gets selected by Rescuezilla's 'Graphical Fallback Mode' when a computer doesn't support the standard boot. Many users might remember of "Windows Safe Mode" which also uses low-resolution VESA mode.

When Rescuezilla is booted using the 'Graphical Fallback Mode' boot menu option or if you're booting on hardware that's not well-supported, there may only be 1 resolution available. However with the latest version of Rescuezilla this should generally be very rare: I have found Linux open-source display drivers to be surprisingly good, at least for 2D / non-gaming related usage.

**Comment by GralfR** [comment]
one vote from me, too.
There are a lot of systems which could be revived with linux that have a low resolution (laptops for example) and the nice rescuezilla-GUI has enough space to be reduced like the very big headline with the huge logo. This could be placed in the upper right or even lower left corner. This would gain enough space for lower resolutions. Keep in mind: even the typical HD 720p with 1280x720 is too small for resuezilla.

**Comment by shasheene** [comment]
Yep definitely will be fixing this for next release (v2.2 scheduled for May 2021).

The easiest and best solution is just a vertical scrollbar over the whole application.

As you said, ideally reducing or remove the Rescuezilla logo banner on lower resolution systems will also help. I'll look into that!

**Comment by shasheene** [comment]
Fixed in [Rescuezilla v2.1.3](https://github.com/rescuezilla/rescuezilla/releases/latest)!
