### ISSUE TITLE
Add ability to make screen capture / print screen to a file

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#166]
A user has suggested adding screen capture functionality:

> I was thinking that it might be worth adding the ability to take screen-captures in Rescuezilla. That might be a useful tool for the average user to visually track the progress of their backup/restore process if they are running into issues. (if it is already available in Rescuezilla, it didn't work for me...) That way they can send you something that might give you clues to what they or the program is doing wrong. Especially if they can't figure out how to export the logfile.txt to the desktop. Likely a low priority but just a thought. 

This is indeed a good idea. It definitely should be bound to the standard keyboard button for "Print Screen" with a user-interface element to make saving the file (to eg, Desktop) easy.

I tend to use `scrot` but it's definitely difficult to use compared to `gnome-screenshot`. The task is to determine the best application and integrate it into the Rescuezilla live ISO.

**Comment by FluorescentGreen5** [comment]
Saving to the Desktop might be a problem if they can't boot into the internal OS, so you might want to consider adding a feature that allows for saving to the root of the thumb drive so that the user can easily find it when they plug it into a working system to report it.

Note that this might be difficult for users that flashed their ISO with YUMI or another flashing tool that supports multibooting, so maybe add a notice saying that it's not guaranteed to be available if another flashing tool was used.

**Comment by shasheene** [comment]
Yeah, given Rescuezilla is [currently non-persistent](https://github.com/rescuezilla/rescuezilla/issues/8) it makes sense to save screenshots to an external USB stick as anything saved to the desktop won't persist between reboots.

Ideally the screenshot utility would have an easy way to upload the screenshots and open a new support query on the [support forum](https://sourceforge.net/p/rescuezilla/discussion/support/). I think this would help users greatly (but vastly increase the time I spend on user-support). Doing this would require me to modify the `gnome-screenshot` application. I will determine the feasibility of this.
