### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by tkatsageorgis** [rescuezilla/rescuezilla#171]
Hello,

please find attached a zip

[el.zip](https://github.com/rescuezilla/rescuezilla/files/5851749/el.zip)

 file containing 3 files translated for Greek lang

**Comment by shasheene** [comment]
Great work, tkatsageorgis!

The next version is Rescuezilla v2.2 scheduled for May 2021 which is too far away, **so I have created a build that's simply Rescuezilla v2.1.2 plus your translation: [rescuezilla-2.1.2-3-g7b1bf333-64bit.groovy.iso](https://drive.google.com/uc?id=1R-_Mq3SrVcvRyL1YPPA5R6m--oeZLqLf&export=download).** Feel free to distribute it on forums or anywhere else, as you see fit.

I have selected the standard Greek keyboard. Let me know if this is not sufficient because there were some Greek keyboard variants such as "simple", "extended", "nodeadkeys" and "polytonic" that I didn't select. Here are the screenshots:

<a href="https://user-images.githubusercontent.com/1414379/105454175-5b066c80-5cd1-11eb-8178-6c2b9cae6081.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/105454175-5b066c80-5cd1-11eb-8178-6c2b9cae6081.png"></a>
<a href="https://user-images.githubusercontent.com/1414379/105454179-5cd03000-5cd1-11eb-8889-192a20e92750.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/105454179-5cd03000-5cd1-11eb-8889-192a20e92750.png"></a>
<a href="https://user-images.githubusercontent.com/1414379/105454182-5d68c680-5cd1-11eb-8d02-3c654556cb93.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/105454182-5d68c680-5cd1-11eb-8d02-3c654556cb93.png"></a>

Here are the checksums for this build, if anybody is interested:

sha256sum:
04cbc4f9612a76a1b9e826b8bac87c64c10e02aad981faaac115aa5eecabd657  build/rescuezilla-2.1.2-3-g7b1bf333-64bit.groovy.iso

sha1sum:
7270ccca2f579ed6f23bf28fcddab02b3c81ddd1  build/rescuezilla-2.1.2-3-g7b1bf333-64bit.groovy.iso

md5sum:
c2e75f016ca5f70c60ebc60848098872  build/rescuezilla-2.1.2-3-g7b1bf333-64bit.groovy.iso

Download: [rescuezilla-2.1.2-3-g7b1bf333-64bit.groovy.iso](https://drive.google.com/uc?id=1R-_Mq3SrVcvRyL1YPPA5R6m--oeZLqLf&export=download)

**Comment by tkatsageorgis** [comment]
Hello there. it looks just fine - except from the first screen.
The 2nd and 4rth option do not display fully. Do you want to try these
alternatives?

"Εναλλακτική λύση γραφικών" instead of  "Λειτουργία εναλλακτικής λύσης
γραφικών"

"Έλεγχος ελαττωματικών USB" instead of  "Ελέγξτε για ελαττωματικές θύρες
USB"

**Comment by shasheene** [comment]
Done! 

I have replaced the links/screenshots/checksums above with a new version with the shorter text:

<a href="https://user-images.githubusercontent.com/1414379/105489414-1abfe200-5d03-11eb-9193-01fef24e29d9.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/105489414-1abfe200-5d03-11eb-9193-01fef24e29d9.png"></a>

Download: rescuezilla-2.1.2-4-gdcc21a8d-64bit.groovy.iso

**Comment by tkatsageorgis** [comment]
It looks even better now.😉. Thanks!!!

**Comment by shasheene** [comment]
Since Rescuezilla v2.1.3, the Greek translation is [available in the official release}(https://github.com/rescuezilla/rescuezilla/releases/latest)!
