### ISSUE TITLE
Btrfs drives without partitions are not shown as backup targets

### ISSUE THREAD

**Issue by joshontech** [rescuezilla/rescuezilla#175]
I have 3 drives formatted as btrfs but I have the whole drive as btrfs with no partitions. When selecting a drive to backup my 3 btrfs drives show up to select to backup but when I get to the target drive for the backup to write to those drives are not listed. I can see my other btrfs drives that have partitions formatted as btrfs so I know it's not an issue with btrfs in general. 

This may be a tall order but I would request you look into btrfs send/receive as maybe an option to add to your program to deal with all btrfs transactions. I know btrfs is not popular on the main stream but I feel it would be great to be able to easily do this in a gui. 

I use send/receive all the time on my btrfs systems but it would be nice to have this option in a backup solution like rescuezilla. Sorry I am not a programmer so I don't know the ins and outs of how hard something like this would be to impliment but I thought I would put it out there 😁

If you do wanna try this and need a tester I am your guy just let me know and I'll test anything you need. 

Thanks for the great backup solution!

**Comment by shasheene** [comment]
Hi Josh,

By the way, this kind of support discussion is better done on the [Rescuezilla forum hosted on Sourceforge](https://sourceforge.net/p/rescuezilla/discussion/) (the GitHub issues are for focused tasks with clearer scope).

It sounds like the issue here is around whether your filesystem resides on a partition table (eg, /dev/sda3) or directly on a disk (eg, /dev/sdb). I intend to improve support of [filesystems directly on disk as part of task #43](https://github.com/rescuezilla/rescuezilla/issues/43).

As per the [Rescuezilla Project Roadmap](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Project-Roadmap) in the longer term I hope to provide expert users with the ability to create backups using alternative modes (eg, use 'ntfsclone' over 'partclone' for NTFS filesystem) just like Clonezilla already does. This will of course require careful user-interface design. I'm not yet familiar with the internals of Btrfs yet. While I am generally open to including Btrfs specific modes, maintaining full interoperability with the industry-standard Clonezilla project definitely takes precedence over any features that would act as incompatible extension.

Thanks for the offer to be a tester. At this stage I'm trying to reduce the long-term human testing burden by creating an [automated testing suite for long-term maintainability (task #151)](https://github.com/rescuezilla/rescuezilla/issues/151), but human testing / bug reports / feedback is always appreciated (ideally on the [Rescuezilla forum hosted on Sourceforge](https://sourceforge.net/p/rescuezilla/discussion/))

**If you like Rescuezilla, the best thing you can do is [give the project a "like" on AlternativeTo](https://alternativeto.net/software/rescuezilla/)**. Hopefully the project can get much closer to Clonezilla's 413 likes so that more people can discover it!
