### ISSUE TITLE
Japanese Translation of Rescuezilla

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#176]
I wanted to contribute as much as I could to Rescuezilla to show my appreciate for all of the time and effort it has saved me. Even if it won't be utilized, I translated Rescuzezilla in Japanese for practice and hopefully down the line it would help someone. I'm pretty sure I followed the template correctly.
[Japanese.zip](https://github.com/rescuezilla/rescuezilla/files/5861040/Japanese.zip)

**Comment by shasheene** [comment]
Great work @AE720!

I have integrated your work. I'm sure it will provide a great basis for a native speaker to polish into idiomatic Japanese (Cunningham's Law). I've studied Japanese for many years, but I'm so rusty that I can't remember the difference between 選ぶ and 選択する, so I won't be any help here. **Hopefully somebody anybody reading this who is a native Japanese speaker could download the following files and make any changes as required**:
    * [src/livecd/image/boot/grub/locale/ja.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/livecd/image/boot/grub/locale/ja.ko)
    * [src/apps/rescuezilla/rescuezilla/usr/share/locale/ja/LC_MESSAGES/rescuezilla.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/apps/rescuezilla/rescuezilla/usr/share/locale/ja/LC_MESSAGES/rescuezilla.ko)
    * [src/apps/graphical-shutdown/graphical-shutdown/usr/share/locale/ja/LC_MESSAGES/graphical-shutdown.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/apps/graphical-shutdown/graphical-shutdown/usr/share/locale/ja/LC_MESSAGES/graphical-shutdown.ko)

For keyboard input, I've installed ibus-anthy but I have not done any configuration yet. Supposedly, ibus-mozc (based on Google Japanese Input) is increasingly popular. For display of characters, I've decided to install [fonts-takao-mincho](https://en.wikipedia.org/wiki/Help:Installing_Japanese_character_sets#Debian_and_Ubuntu) but not the larger [fonts-takao](https://packages.ubuntu.com/focal/fonts-takao) metapackage. I'll need to do more research on benefits/tradeoffs of these packages, and the differences in their installed size.

Download: **I have created a build that's simply Rescuezilla v2.1.2 plus your translation (and the recent Greek translation): [rescuezilla-2.1.2-5-gb3dc8626-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1hxKBj8kkW3NvU7omL4AsNaKaebnto4-H&export=download).**

Checksums: 
sha256sum:
bb24fd9d5664b534fa8ebcfc094c25230e237eece347626e3673a8d14a2d77fd  rescuezilla-2.1.2-5-gb3dc8626-64bit.groovy.iso

sha1sum:
8b27dc73850cd30d7de30d23944748b0da2fec2f  rescuezilla-2.1.2-5-gb3dc8626-64bit.groovy.iso

md5sum:
28f85150a7df90dc34e99b987d92038c  rescuezilla-2.1.2-5-gb3dc8626-64bit.groovy.iso

Screenshots:

<a href="https://user-images.githubusercontent.com/1414379/105622901-24f9f180-5e65-11eb-916e-649a06b51dda.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/105622901-24f9f180-5e65-11eb-916e-649a06b51dda.png"></a> <a href="https://user-images.githubusercontent.com/1414379/105622902-26c3b500-5e65-11eb-9c91-ca240f673a46.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/105622902-26c3b500-5e65-11eb-9c91-ca240f673a46.png"></a>
<a href="https://user-images.githubusercontent.com/1414379/105622903-275c4b80-5e65-11eb-86a2-9d0689312efd.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/105622903-275c4b80-5e65-11eb-86a2-9d0689312efd.png"></a>

You've already gone way above and beyond for this project, but if you haven't already [please consider giving the project a "like" on AlternativeTo](https://alternativeto.net/software/rescuezilla/). Hopefully the project can get much closer to Clonezilla's 413 likes so that more people can discover it!

**Download: [rescuezilla-2.1.2-5-gb3dc8626-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1hxKBj8kkW3NvU7omL4AsNaKaebnto4-H&export=download)**

**Comment by AE720** [comment]
Sounds good. A fair chunk of them I derived directly from real world examples such as error messages for other programs/operation systems as well as a dictionary that has tags stating it's computer terminology. Even if I can't be 1000% sure since of course I'm not a native speaker, I do know it's been combed through thoroughly. Hopefully someone can skim it and say it's good to go.

**Comment by shasheene** [comment]
Since Rescuezilla v2.1.3, the Japanese translation is [available in the official release](https://github.com/rescuezilla/rescuezilla/releases/latest)!

**Comment by FX8350** [comment]
Hello.
Thank you for your wonderful software development.
I am a native Japanese speaker. And I've updated the translation.
Much respect to AE720, the original translator.
[JA.zip](https://github.com/rescuezilla/rescuezilla/files/6134503/JA.zip)

**Comment by shasheene** [comment]
Thanks for the updated translation, @FX8350.

The only thing I noticed is the "Graphical fallback mode" item in the boot menu is 1 character too long:

>  msgid "Graphical fallback mode"
> -msgstr "グラフィカルなフォールバックモード"
> +msgstr "グラフィカルフォールバックモード"
>  #      "----------MAX-LENGTH----------"

Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/1414379/111027440-48422580-8440-11eb-9375-6559203c718f.png)

As you've already know the purpose of that menu item is for Rescuezilla to use a low-resolution fallback graphics driver when the standard mode doesn't work.

Is there a more compact translation that also means "fallback video mode"?

**Comment by FX8350** [comment]
Thanks for the reply and review.
"フォールバックビデオモード", which is katakana for "fallback video mode", would probably be more compact.
~~~ msgid  "Graphical fallback mode"
 msgstr "フォールバックビデオモード"
        "----------MAX-LENGTH----------"
~~~
[JAv2.zip](https://github.com/rescuezilla/rescuezilla/files/6134701/JAv2.zip)

This is the modified ja.ko.

**Comment by shasheene** [comment]
Thanks! I have integrated the translation. Your changes will be released as part of the next Rescuezilla update. This is most likely going to be v2.2, which is scheduled for May 2021.

There's actually going to be a lot of new features in the v2.2. I am hoping to complete a new mode for cloning / device-to-device operation. Once I have completed everything there will be a few more strings to translate.

To make it as easy as possible for translators, I am investigating switching to [Weblate](https://hosted.weblate.org/) (or a similar application).

**Comment by FX8350** [comment]
Thanks integrate translate!
I'm looking forward to the next release!

**Comment by shasheene** [comment]
@FX8350  Actually May 2021 is definitely still too far away, so I will make a new unofficial version with your updated translation, like I did before with the original translation.

It will be ready as soon as I've finalized one line of the recent update to the Chinese (Simplified) translation, so it should be released below within the next day or two.

**Comment by shasheene** [comment]
OK, the next version is Rescuezilla v2.2 scheduled for May 2021 which is too far away, so I have created a build that's simply Rescuezilla v2.1.3 plus the translation updates: [rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1KMwn0OnxqX-6pqnv5Mf0E9YT569xZ9p9&export=download). Feel free to distribute it on forums or anywhere else, as you see fit.

<a href="https://user-images.githubusercontent.com/1414379/111443664-851c5e00-8759-11eb-934e-1723cd7c97ac.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/111443664-851c5e00-8759-11eb-934e-1723cd7c97ac.png"></a>

Checksums:
sha256sum:
6347d98174452d634af42d0cebec7f96222d7d3e6deff9f69a972c93a8d9b11c  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

sha1sum:
d739707c5d95e02d82b235cbd059e3bd6a8f09b8  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

md5sum:
9bcae3d3eaff6f062ba07067afa25af4  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

Download: [rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1KMwn0OnxqX-6pqnv5Mf0E9YT569xZ9p9&export=download)

**Comment by FX8350** [comment]
Thanks for the build!
I have tried to backup and restore a typical system (Windows 10 installed on NVME SSD,backup to External HDD).

I have a few reports.
SETEP 4 of Restore has not been translated.

```
msgid "Step 4: Select Partitions To Restore"
msgstr "ステップ 4: レストアするパーティションを選択します"
```

I've updated some translations, should I upload them here, pull request them, or wait until v2.2 is released?

**Comment by shasheene** [comment]
Sorry I missed that step 4 wasn't translated. Please download the following files and make any changes you'd like:
    * [src/livecd/image/boot/grub/locale/ja.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/livecd/image/boot/grub/locale/ja.ko)
    * [src/apps/rescuezilla/rescuezilla/usr/share/locale/ja/LC_MESSAGES/rescuezilla.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/apps/rescuezilla/rescuezilla/usr/share/locale/ja/LC_MESSAGES/rescuezilla.ko)
    * [src/apps/graphical-shutdown/graphical-shutdown/usr/share/locale/ja/LC_MESSAGES/graphical-shutdown.ko]
    
Then upload the files here and I'll integrate them and make a new build!

**Comment by FX8350** [comment]
Here is the updated translation.
More user-friendly the Japanese translation
[JAv3.zip](https://github.com/rescuezilla/rescuezilla/files/6156626/JAv3.zip)

**Comment by shasheene** [comment]
I've integrated your latest updates. I have also fixed the issue where the Restore Step 4 title was not displaying. The problem was actually affecting every single translation. Thanks for pointing it out!

Here is a link to the new build: [rescuezilla-2.1.3-13-g906d8b87-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1nbTCTMzQSNGQKdEkVOKqoMaU_59GHJIs&export=download). I have updated the previous links and checksums to point to this new version.

sha256sum:
bf4b2d60f5fa4b2298449de09a363dfc1b4010d073651ba3a4417768102f4b7f  rescuezilla-2.1.3-13-g906d8b87-64bit.groovy.iso

sha1sum:
ee3a2a152c17b35aaf58fb8ba9116b2ceb593256  rescuezilla-2.1.3-13-g906d8b87-64bit.groovy.iso

md5sum:
db89e8bae1111f4fdf1a449a0da1850a  rescuezilla-2.1.3-13-g906d8b87-64bit.groovy.iso

By the way, please be very careful when making a backup of a Windows 10 system by carefully reading the backup summary. I believe there's a situation that can affect a small number of Windows 10 machines where the filesystem might be locked causing the backup to fail. This fact is displayed to the user, but it's still definitely not ideal. I hope to improve the situation for the next version.
