### ISSUE TITLE
Spanish update for es.ko

### ISSUE THREAD

**Issue by caralu74** [rescuezilla/rescuezilla#188]
Into my branch I have some missing lines. So I think you should prefer this file.
[es.txt](https://github.com/rescuezilla/rescuezilla/files/5962098/es.txt)

**Comment by shasheene** [comment]
Thanks! The reason those very long help text sentences weren't yet translated is because they won't be displayed in modern versions of Rescuezilla until task #76 has been completed (which still might be a _long_ time away). It's definitely still very useful text, but there's currently no way to display it.

I have integrated your update. **Please note, there is one menu item that is too long so is being cut-off** when booted using the BIOS method. Here is the screenshot and translation:

![es](https://user-images.githubusercontent.com/1414379/107598776-babbbc00-6c6e-11eb-97cd-f788173f6841.png)

```
msgid "Check USB for defects"
msgstr "Comprobar si hay defectos en la USB"
```

The translation is only 4 characters too long. **If there's any way to reword that line to fit within the length limit, please do!** 

Side note: I will update the boot menu translation file for all translations to make the exact length limit much more clear, so that translators will reword their sentences accordingly.

**Comment by pfrouleau** [comment]
@shasheene I saw a "typo" in `build.sh`: there is a "$long" instead of "$lang".

```
        if [[ ! -f "$lang.ko" ]]; then
                echo "Warning: $long.ko translation does not exist. Skipping."
#                              ^^^^^
```

**Comment by shasheene** [comment]
OK, merged the changes so far, so I am closing this issue.

@caralu74 if you are interested, please have a look at the "Check USB for defects" line of [es.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/livecd/image/boot/grub/locale/es.ko). I have added a maximum length comment to certain boot menu items, and that's the only one that's being exceeded for the Spanish translation.

**Comment by caralu74** [comment]
Sorry for the late. I fix the "check USB..." I think now is OK.
[es_updated.txt](https://github.com/rescuezilla/rescuezilla/files/6016159/es_updated.txt)

**Comment by shasheene** [comment]
Yes it's good now. Thanks!
