### ISSUE TITLE
RescueZilla won't run

### ISSUE THREAD

**Issue by Andy2051** [rescuezilla/rescuezilla#21]
Built iso, booted fine, chromium, xrandr, file manager all work, rescuezilla doesn't. From the logs:

```
Global symbol "$part" requires explicit package name (did you forget to declare "my $part"?) at /usr/local/sbin/rescuezilla line 1342.
Global symbol "$data" requires explicit package name (did you forget to declare "my $data"?) at /usr/local/sbin/rescuezilla line 1343.
Execution of /usr/local/sbin/rescuezilla aborted due to compilation errors.
```
Note that rescuezilla is 32bit and running it on a 64 bit machine if relevant.

**Comment by shasheene** [comment]
Hi Andy2051,

Thank you for bringing this to my attention. Since I tagged 1.0.5 last week, I accidentally pushed some not-yet-ready commits that are being developed for a future v1.0.5.1 release. I am reverting the problematic commit.

Please fetch the latest changes, and rebuild the ISO image. This should be relatively fast given you have already downloaded the deb packages.
```
git fetch
git rebase origin/master
sudo make```

Since you are building an ISO image from source, you may not have seen the v1.0.5 Bug Advisories section on the release page. Please read that and take care to avoid the highest severity bug (#16). Incidentally that is the bug which the change I am reverting was originally intended to fix.

I am switching to exclusively using GitHub Pull Requests to allow some sanity checking before changes are merged. This should stop myself pushing not-yet-ready for release commits.
