### ISSUE TITLE
Translation Question...

### ISSUE THREAD

**Issue by AliensInc** [rescuezilla/rescuezilla#214]
Is a blank field in translation the same as show the original language, thus English?
'cos that will mark the items as not translated, also marked RED if I write the same thing, like gzip can't really be translated :P

btw, found some error in my previous so I was thinking of correcting that and saw there was a lot more so have been doing that for a while. Will rest a bit though, my shoulders _feels_ it ;)

**Comment by shasheene** [comment]
A blank field does show the source sentence (in this case English). As far as Weblate goes, there should be away to mark it as translated, but I'm not sure.

I see you've recently done a lot of work on the Swedish translation. Thanks!

As for any errors, you can freely correct the translated sentences as much as you'd like. Rescuezilla v2.2 will be released at the end of May 2021.

Don't stress: now that Weblate makes it much easier to manage translations going forward, it's much, much easier to spread to burden of translation and review across multiple speakers of a given language.

**Comment by AliensInc** [comment]
I'll be checking for that _mark as done_ thingy later.

Now just chillin with a pizza and some tveps, later some computer fiddling, a new Pure Arch machine to be installed.
But as I now know this Weblate site which is as you say so easy, I'll be continue hacking some more translations :)
Done! before the end of May.

Have a good evening/night, Sir :D

**Comment by shasheene** [comment]
You too!

Weblate definitely has a user-interface that's difficult to understand that needs a lot of improvements. But it's definitely a net improvement to managing text files!

I have created a label titled "NO_NEED_TO_TRANSLATE". If there isn't any way to mark a translation, we can always set that label (and then I will use the Weblate administrative tools to bulk search and mark translated). I'll post an update below if I determine a better way!

**Comment by AliensInc** [comment]
OK, one thing left and that is: zstandard
I added into the glossary with the comment.

Also, please tell people to STOP!!! using translategoogle, cos that sux in like 30..40% of the time.
It all differs what language but, that's a no no.

**Comment by shasheene** [comment]
Oh the "Suggestions" tab using Google translate was added by me by using Weblate's internal tools because the very clear "Automatic Suggestions" tab only appears for logged in users:

![automatic translation](https://user-images.githubusercontent.com/1414379/119082140-9bd28000-ba3c-11eb-8a82-82d98a5e08c9.png)

My reasoning was for translations that require multiple sentences, it's easier to review a broken Google Translate than type the sentence from scratch. I will remove the "Suggestions" tab on the completed translations, as I see you have already done for the Swedish translation.
