### ISSUE TITLE
Rescuezilla frozen from start

### ISSUE THREAD

**Issue by PhoenixIV** [rescuezilla/rescuezilla#218]
The UI does not react on my system at all. Version 2.1.3 [late edit! I wrote 3.1.2 by accident], I verified the hashes and flashed to two different drives.

**Comment by shasheene** [comment]
Hi @PhoenixIV,

As of writing the most recent version of Rescuezilla is v2.1.3. It sounds like you've tried to write the Rescuezilla ISO image to a USB stick but this stick isn't booting on your computer?

Do you see Rescuezilla's initial language selection screen? When booting into Rescuezilla USB stick you may need to repeatly press a button such as Esc, F8 or F12 to reach the 'one-time boot menu' to boot from USB stick.

What are the specification of your computer? (Rescuezilla v2.2 will be released in a few days and will be built upon Ubuntu 21.04 (Hirsute) which will provide better support for very recent hardware.

**Comment by PhoenixIV** [comment]
I am sorry I did not explain well what I see on my screen:
I get all the way up to the Desktop, upon which it takes half a minute until the Rescuezilla UI is visible. Before it is visible the black top bar with its name and the open, close, minimize is already visible, but below that the wallpaper with the desktop icons. The mouse can move.
When the Rescuezilla UI is then visible (Backup & Rescue buttons in the middle) nothing seems to react / is clickable. Also after minutes.

For comparison: I tested Redorescue and that worked, as well as other Linux systems.

> Rescuezilla v2.2 will be released in a few days and will be built upon Ubuntu 21.04 (Hirsute) which will provide better support for very recent hardware.

Nice. Maybe that will solve my issue automatically. My hardware is from 2014: Intel i5 4690 on motherboard Asus z97-P.

Thank you for being nice even tough my initial ticket was not containing enough information.

**Comment by shasheene** [comment]
Hardware from 2014 should definitely have good support with Rescuezilla v2.1.3. (It's only hardware made in the last 6-12 months that will generally have problems if not using the most recent version of Ubuntu).

Could you please try running Rescuezilla v2.1.3 again just to test if it gets to the desktop?

I think there might be a timing issue between Openbox Window Manager and the PCManFM desktop so a reboot might temporarily resolve it.

**Comment by PhoenixIV** [comment]
🤦‍♂️ Oh, I did not notice I confused numbers. I tested 2.1.3, not the non-existent 3.1.2.

Issue described above.

**Comment by PhoenixIV** [comment]
If you could compile a 2.2 preview for me I am happy to test this one!

**Comment by shasheene** [comment]
I have not yet finished rebasing the project onto Ubuntu 21.04 "Hirsute" (April 2021) from the Ubuntu 20.10 "Groovy" (October 2020), so I don't yet have a build for you.

If you would like a different build to test, the only other thing you might want to try is [the v2.1.3 build based on Ubuntu 20.04 "Focal (April 2020)](https://github.com/rescuezilla/rescuezilla/releases/download/2.1.3/rescuezilla-2.1.3-64bit.focal.iso). The fact packages are older versions in that build may provide different results.

**Comment by PhoenixIV** [comment]
Thanks for the link!

Same issue with Focal. Additionally that one shows me a "Battery low" warning (Desktop PC with no batteries).

I will wait for 2.2 and then test again. Maybe even without graphics card (onboard then).

**Comment by shasheene** [comment]
OK, sounds good. Sorry for any inconvenience. I'll post a comment here in a few days once v2.2 is released!

**Comment by shasheene** [comment]
@PhoenixIV I forgot to ask, have  you tried the "Graphical Fallback Mode" option on Rescuezilla v2.1.3?

**Comment by PhoenixIV** [comment]
No, I have not - I just did! (I was blind for any startup options....)

It works with fallback mode in Groovy right away.

**Comment by PhoenixIV** [comment]
Isn't Ubuntu quite a huge system in file size for what is required?

**Comment by shasheene** [comment]
Rescuezilla always has a release available under Ubuntu LTS release. For Rescuezilla v2.1.3 it's the ISO named "focal" referring to the Ubuntu 20.04  LTS (Focal Fossa). You'll need to scroll to the bottom of the releases page to see this (under the 'Assets' section). I recommend users use the non-LTS release, because it provides better support for modern hardware and is very stable itself (makes sense given how popular it is).

I'll be releasing a version based on Debian at some point, but it actually doesn't make any significant difference. The many graphical tools, language packs and powerful such as qemu-nbd, nbdkit and Firefox are what cause Rescuezilla to have such a large filesize. The reason Clonezilla is so tiny is it doesn't have a graphical user interface and web browsers etc.

If you want just the smallest possible Rescuezilla download, you can download 300kb (yes kilobyte) deb file from the releases page. But you need to first add 'nbd' to /etc/modules and install `smartmontools`. Though it has about 200MB of dependencies it downloads from apt-get. I could make some dependencies "suggested" not "required" in future.

Either way, I recommend you wait until Rescuezilla 2.2 is released (in less than 48 hours) before heavily testing Rescuezilla. There's a huge amount of improvements, features and bug fixes!

**Comment by shasheene** [comment]
I am closing this issue since the workaround of 'Graphical Fallback Mode' has been determined. The problem most likely lies with the Linux kernel and its drivers. Possibly there's a missing package but this is unlikely since I don't believe any users have reported the issue for the Groovy build since release.

I'm happy to provide an improved fix if one becomes apparent, but hopefully the Hirsute build removes the need for 'Graphical Fallback Mode',
