### ISSUE TITLE
[Solved] There is no Redo Backup v1.0.5 ISO image on Github !

### ISSUE THREAD

**Issue by jazbina** [rescuezilla/rescuezilla#24]
Where is Redo Backup v1.0.5 ISO image ? Every link leads to github and there is no image here.
Why you did not put file on https://sourceforge.net/projects/rescuezilla/

**Comment by jazbina** [comment]
I am blind.. it was under Assets.
But really you could  `wget https://github.com/rescuezilla/rescuezilla/releases/download/1.0.5/redobackup-livecd-1.0.5.iso
`

**Comment by shasheene** [comment]
Hi jazbina,

The ISO image link is indeed hard-to-find because the Assets section is collapsed by default.

Rescuezilla (formerly _Redo Backup and Recovery_) is best managed on GitHub. If the current maintainer ever disappears (like in the case of the original Redo Backup author), the fact the project is hosted on GitHub provides a lowest friction way for a new maintainer to simply fork both the project and rescuezilla.com website (via GitHub Pages) in order to continue development.

The Rescuezilla Sourceforge _user_ account is to provide support on the Redo Backup project (including the long and tedious process responding to all 400 forum threads). The Rescuezilla Sourceforge _user_ account is just a placeholder and helps redirect users to GitHub. It makes the most sense to keep all releases in one place.

**I might make the link to the ISO image easier to find when Rescuezilla is more mature.** However, the v1.0.5 still has one high priority bug. I have had other priorities gnawing at my time recently, so I haven't yet had a chance to fix the bug, test it and release v1.0.5.1. The bug advisory table is very important so please consult it (on the Releases page), and take care to avoid reproducing the error.

Please enjoy Rescuezilla, and for fast booting please always use a USB stick, not a CD/DVD!
