### ISSUE TITLE
Speedup boot time

### ISSUE THREAD

**Issue by Shine753** [rescuezilla/rescuezilla#243]
Rescuezilla can be used on old systems.
For example, when I try to use it on a Q9450 machine, with 5 Gb RAM, installed onto a fast USB 3.1 key on a USB 2.0 port, it boots in 4mn23s.
As a comparison, with same all, a Linux Mint 18.3 xfce boots in 2mn30.
And a Linux Mint 20.1 xfce boot in something like 6mn30.

Anything you could make to reduce the boot time would be great.
As an idea, I've heard that grub is a big part of that boot time and there exist other bootloaders that are way faster.

**Comment by shasheene** [comment]
Interesting. That is an excessively slow boot on an older Intel Core 2 Quad Q9450 CPU.

It could be that the speed difference is due to Rescuezilla v2.2 switching to compressing the root filesystem using 'zstandard' compression at level 19 (https://github.com/rescuezilla/rescuezilla/issues/161). But 'zstandard' claims to have similar decompression speed as 'gzip' (which was used to compress the root filesystem on Rescuezilla v2.1.3).

It's unlikely the GRUB bootloader itself contributes to the boot time beyond at most a few seconds (after the language selection it should have no impact at all).

**If you are interested, please test the boot speed of [ Rescuezilla v2.1.3](https://github.com/rescuezilla/rescuezilla/releases/download/2.1.3/rescuezilla-2.1.3-64bit.groovy.iso)**. This will easily rule out whether the root cause is the 'zstandard' compression change. Don't use Rescuezilla v2.1.3 for anything other than testing the speed of the boot, as Rescuezilla v2.2 has made many improvements and bug fixes.

**Comment by Shine753** [comment]
Tried with Rescuezilla v2.1.3, same configuration :
Kernel starts to boot at 5mn40s and almost instantly crashes in a Kernel panic :
![IMG_8742](https://user-images.githubusercontent.com/37425160/124392315-16a5e080-dcf5-11eb-8095-95524f5e000a.JPG)

**Comment by Shine753** [comment]
For example, today, same boot with Rescuezilla v2.2 than my original post (I just have added Rescuezilla v2.1.3 to the USB drive for the above test) : it did boot in 6mn50s, and the Kernel started to boot at 5mn

**Comment by shasheene** [comment]
Thanks for confirming the 5m40s figure. That indicates it's definitely not an issue with switching to zstandard root filesystem compression.

I'm not too concerned about the kernel panic: Rescuezilla v2.1.3 is based on Ubuntu 20.10 (Groovy), which has been replaced by the 21.04 (Hirsute) version for Rescuezilla v2.2. You have confirmed v2.2 works, so the newer Linux kernel included in that version likely fixed a bug.

Also, something you mentioned earlier:

> As a comparison, with same all, a Linux Mint 18.3 xfce boots in 2mn30.
> And a Linux Mint 20.1 xfce boot in something like 6mn30.

This definitely indicates that the slow down that has been introduced by something within the Ubuntu-base used by both Rescuezilla and Linux Mint.

**Given this, unfortunately there is very little I can do for this particular case: it will take improvements to Ubuntu itself for both Rescuezilla (and Linux Mint) to boot as fast on that hardware like previous versions did. I'm not sure which specific Ubuntu component has the issue, but there is likely already bug report somewhere noting this issue.**

**Comment by shasheene** [comment]
Since the unmodified live environment of a major Linux distribution like Linux Mint experiences the exact same issue on your hardware, it's not something I intend to investigate.

But once the major Linux distributions have resolved the issue, if Rescuezilla still experiences the issue then I will investigate.

**Comment by Shine753** [comment]
Thank you

**Comment by oam7575** [comment]
For what its worth I have carried out a test booting a vm via my PXE environment.
As the issue was reported speed / throughput problem I limited the VM to 1x vCPU core and 200Mhz of cpu time.
The HOST system is only an i3-7100T so not all that powerful at any rate.

The guest booted via Gbit PXE in about 5 mins.

Considering a possible timeout problem I bumped the vm to 500MHz cpu time, but limited network bandwidth to about 10Mbits.

I did walk away for a while; however the vm still booted from PXE and was online when I returned after about ~30  minutes

Considering the error report and the low performance of the vm and the successful testing I would be thinking the problem most likely is with the hardware.

Either problems with the USB port, North Bridge chip, RAM that is on the way out or the USB key .

Of course this is all speculation and hard to say for certain either way.
