### ISSUE TITLE
backup verification

### ISSUE THREAD

**Issue by ttt113326** [rescuezilla/rescuezilla#269]
Just yesterday (for reason 265) I copied the backup files to a very old HDD and started restoring. It looks like there was a bad sector on the disk or for some other reason? But I couldn't restore Linux - the restore stopped with an error in the middle of the process. I ask a question: how can I check the backup files for errors before starting the restore?
Can make the Verify button look like Redo Rescue 3.0.2?
Or, when creating backup files, create txt for each file with SHA256 hash, but then add a program to the liveCD that can get SHA256 hash from files

**Comment by shasheene** [comment]
It's likely there is a bad sector on your source disk or on the destination. The issue you're experiencing will almost certainly be resolved by enabling partclone's `-F` (`--force`) option to "force progress" even during a error like a filesystem inconsistency. It could be a problem on the source drive too, but it's hard to tell.

I am aware of the need to improve Rescuezilla's [handling of drives with bad sectors (task #237)](https://github.com/rescuezilla/rescuezilla/issues/237). As detailed #237, as best I can tell Redo Rescue _always_ uses partclone's `--force` option, but I strongly disagree with that design choice (because it's very dangerous in my view). For Rescuezilla v2.3, I am planning on providing an *option* to enable partclone's `--force` (and partclone's `--rescue`). This will finally improve the handling of your problematic disks using modern versions of Rescuezilla.

Rescuezilla v2.2 does not have the ability to [verify an existing backup (task #30)](https://github.com/rescuezilla/rescuezilla/issues/30), but advanced users can close all windows, open a Terminal, run `clonezilla` and use the Clonezilla tool to conduct the verification of an image created using Rescuezilla (both tools create compatible images)

I actually have created an entire "verify" wizard build into Rescuezilla already, but since Rescuezilla v2.2 added support for so many image formats and I haven't yet exposed the feature to users:

![verify](https://user-images.githubusercontent.com/1414379/136637174-52716f08-6ebe-45f2-8cdf-e8f39e163319.png)

I felt the risk of an image (say, created by Foxclone) being able to pass verification, but not actually being able to be restored would be too great. So releasing the wizard hasn't yet been a high priority. I will try to polish and release this feature for Rescuezilla v2.3!

**Comment by Auronius** [comment]
I think, that image verification is **necessary thing**. Without it I can not be sure, that my backups are made correctly, and will be restored correctly. So, I will wait until this option will be available before starting to use Rescuezilla for creating backups of my computers. Frankly, I was very disappointed, that this essential feature is not available...

**Comment by shasheene** [comment]
Hi @Auronius,

I agree a separate image verification button will be useful lot of people. The previously recommended approach (of closing all windows, opening a terminal and using Clonezilla to verify your images created with Rescuezilla) is definitely inconvenient.

The feature will be part of Rescuezilla v2.3 (to be released in less than 30 _days_).

As always, I will carefully implement the industry-standard Clonezilla behavior (which uses `partclone.chkimg` among many other tools internally) across all image formats that Rescuezilla supports.

Over the years I have seen many users complain of "verify succeeded, but backup failed" situations with other tools, which has made me hesitant to implement the feature. I think the Summary screen details is best. Eg:

> Partition table is restoreable
> Partition 1 is restoreable
> No image associated with partition 2 (user did not back it up?)
> Partition 3 is restoreable

This would just be a start: I an idea around having this "Verify Image" feature check whether backup images could be mounted using partclone-nbd/partclone-utils (but this is overkill for the initial "Verify Image" feature).

Given the nature of Rescuezilla's interface (with its "image folder scanning" step that has significant processing), I am hoping to allow users to select _multiple_ images and verify them at the same time.

Let me know if you have any concerns/feedback with my description above. As mentioned, it will be released with Rescuezilla v2.3 in less than 30 days.

**Comment by shasheene** [comment]
Yep, the Verify feature **will be part of Rescuezilla v2.3 (to be released in less than 30 *days*)**.

Sorry about the unnecessary programming detail/explanation, **my main point there was your existing Clonezilla (and Rescuezilla) images can _still_ be verified by Rescuezilla v2.2 using the following convoluted approach**:

> 1. Close the main Rescuezilla window
> 2. Open the Terminal desktop icon
> 3. Type `clonezilla`
> 4. Highlight "device-image" and press Enter
> 5. Mount your locally attached hard drive using 'local-dev'
> 6. When you see your image folders, click 'Ok'
> 7. Highlight Beginner mode and press Enter
> 7. Highlight 'chk-img-restorable' and press Enter
> 8. Highlight your specific image file and press Enter
> 9. Carefully read the output

Yes, I agree that most users of Rescuezilla will not be using images created with eg, Foxclone.

It's really great to hear that you'll will most likely switch from Clonezilla to Rescuezilla when the Verify feature is implemented!

Thanks for the multiple image selection feedback. I will still try and implement multiple selection, but if it seems overly complex I will simply do the basic single image selection.

**Comment by shasheene** [comment]
@ttt113326 and @Auronius 

Rescuezilla v2.3 is now available.

**It has both the Verify Image button, and it also has a "rescue" option on the confirmation screen**:

![rescue_option](https://user-images.githubusercontent.com/1414379/142799098-8826bc7a-7677-4a26-8dc3-07cce6d3b96d.png)

The "rescue" mode should definitely be a much close match for the beavhior @ttt113326 saw using Redo, but "rescue" is definitely not an option I recommend using unless you have issues with the standard mode.

Both features should be very simple to use, and work very well. Let me know how you go and if you have issues. 

You can verify multiple images at the same time, by the way.

**Comment by Auronius** [comment]
**Yes, Thank you very much!**
Backup verification works very well on **rescuezilla-2.3.1-64bit.impish.iso**, the only thing is, that [swap partition verification is not implemented yet](https://drive.google.com/file/d/1BoTeMirxH2Ujriw8-Xr2j_M7nhWXFHh7/view?usp=sharing). I am not sure, is it important to verify swap partitions? They are almost always empty...

**Comment by shasheene** [comment]
Your backup verification looks good.

Rescuezilla supports a large number of different image formats which each handles swap partitions differently.

The contents of the swap partition are not important: the contents are cleared every reboot.

Rescuezilla uses the same format as Clonezilla where an 8GB swap partition is intelligently saved by creating a small text file which contains the unique identifying number of the swap partition. In other words, only the "metadata". Other tools like Redo Rescue will save the entire 8GB of data.

It's not important to verify swap partitions, but I should probably say something along the lines of "swap partition looks good" and remove the warning icon to be less confusing!!

**Comment by shasheene** [comment]
@ttt113326 I am interested to know if the new 'Rescue' option in Rescuezilla v2.3.1 resolved the issue you were having with earlier versions.

By using the 'Rescue' option you should be able to restore all your images created by Rescuezilla (and Redo Rescue) onto drives with filesystem inconsistencies or bad sectors.

**Comment by ttt113326** [comment]
Hello.  for several months my laptop is not in demand for personal reasons.  no testing in the near future.

**Comment by er013** [comment]
How about avoid all necessity to use rescuezilla or clonezilla for backup verification? Hash all files rescuezilla writes (as they are being created) and create something like allhashes.sha256 or something into that backup directory. Now you can verify files being intact with plain sha256, nevermind clonezilla or rescuezilla being installed.
