### ISSUE TITLE
Spanish translation. (Es-es)

### ISSUE THREAD

**Issue by caralu74** [rescuezilla/rescuezilla#28]
I've translated the 4 files to Spanish for a new Rescuezilla release. 

[Rescuezilla_RedoBackup_ES-es.zip](https://github.com/rescuezilla/rescuezilla/files/3974737/Rescuezilla_RedoBackup_ES-es.zip)
I'll keep an eye on them until they're included in a new version. Thanks in advance!

**Comment by shasheene** [comment]
Thanks for the translation, caralu74. I will integrate this in the next few weeks (once I have a big block of time to develop the v1.0.5.1 release). I have been more busy that I thought the past month or so.

**Comment by shasheene** [comment]
OK caralu74, I have adapted your translation and integrated it.

A release with your translation will be published in the next several weeks. I don't have an estimate on when this will be, but it's coming.

**Comment by shasheene** [comment]
@caralu74, [Rescuezilla v1.0.5.1 is now available (2020-03-24)](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) with your Spanish translation.

![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/1.png)
![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/2.png)
![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/3.png)
![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/4.png)
![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/5.png)
![](https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v1.0.5.1/es/6.png)

Please let me know if you have any issues.

**Comment by caralu74** [comment]
I will try, and ask other persons help as well.
This new version looks nice!
Thanks for your job!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by shasheene** [comment]
@caralu74,

I have released the new version of Rescuezilla. It's a major upgrade adding many new features including full interoperability with the Clonezilla disk imaging software.

The French and German translations were made several years ago before I started developing my revival project. Because I don't have easy contact way to the authors of those translations, I decided to pay money for the translations to be updated (the website quoted $65 US dollars at 10 cents a word).

Then, I made a very stupid decision: I also paid for the Spanish translation to be updated. In hindsight, I could have asked _you_ to update the translation, **and then paid you the $65 US dollars which I paid that third-party translator.** O_O

It was all very stupid of me. Sorry about that.

**Comment by caralu74** [comment]
Sounds a little weird. But if you need something else, Just Call my name and I'll be there...

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
