### ISSUE TITLE
Add warning about multi-part output

### ISSUE THREAD

**Issue by mrx23dot** [rescuezilla/rescuezilla#285]
First time I used rescuezilla I had no idea it will create 5+ files, so I didn't create a new folder for them.

It just creates an extra step for newcomers, also you have to figure out which are the new files and put it into a new dir manually a postmortem.

rescuezilla should be as user friendly as possible, unlike clonezilla.

**Comment by shasheene** [comment]
This issue has already been resolved a long time ago: as you have indicated in the other GitHub issues you have created, you are using Rescuezilla v1.0.6.1, which retained design decisions taken by an old, abandoned application named _Redo Backup and Recovery_ and did not have Clonezilla compatibility.

Since v2.0, Rescuezilla has been rewritten from scratch and has changed a lot of those legacy Redo design decisions, including creating a folder to place the backup files in. Also since v2.0, Rescuezilla creates backups compatible with the industry-standard Clonezilla tool.

**Comment by mrx23dot** [comment]
My bad, could you please maintain a 32bit version for v2 too?

Many of my clients still have 32bit win7, eg factory floor, old accounting PCs, CNC controllers.

**Comment by shasheene** [comment]
> My bad, could you please maintain a 32bit version for v2 too?

No problem, I intend to bring it back. For anybody else reading, here's the link: https://github.com/rescuezilla/rescuezilla/issues/232
