### ISSUE TITLE
Add backup compression/shrinking

### ISSUE THREAD

**Issue by mrx23dot** [rescuezilla/rescuezilla#287]
Doing 1:1 backups are very wasteful on SSD.
Please add compression/shrinking while doing backup.

E.g. Norton Ghost had a perfect compression, it had medium/high settings, even with medium it was able to shrink it to half the size, with minimum time overhead.

It might worth cloning this from Clonezilla.

(rescuezilla is 1000x easier to use than Clonezilla)

**Comment by shasheene** [comment]
A user-interface around compression was added in Rescuezilla v2.2. As you have indicated in the other GitHub issues you have created, you are using Rescuezilla v1.0.6.1, which retained design decisions taken by an old, abandoned application named _Redo Backup and Recovery_ and did not have Clonezilla compatibility.

Since v2.0, Rescuezilla has been rewritten from scratch and has changed a lot of those legacy Redo design decisions, including adding the ability to customize compression like Clonezilla provides. Also since v2.0, Rescuezilla creates backups compatible with the industry-standard Clonezilla tool.

To re-iterate: backups created using Rescuezilla v1.0.6.1 and earlier can be restored with modern Rescuezilla versions, but not with Clonezilla. Because Rescuezilla only started creating backups compatible with Clonezilla from v2.0.
