### ISSUE TITLE
BUG Using Rescuezilla with Ventoy

### ISSUE THREAD

**Issue by vinifrancosilva** [rescuezilla/rescuezilla#295]
Hello,

First, thank you for creating and maintaining this project as an open source project. Great project!

I think I found a bug in rescuezilla when loaded with Ventoy.

I tried to make Verify an imagem created with clonezilla and tried a backup and when selecting my external hd I get a error message 

Falha ao executar comandos: umount /dev/mapper/ventoy 
umount: /cdrom: o alvo está ocupado.

Fail to execte command: umount /dev/mapper/ventoy 
umount: /cdrom: target is not available

![Screenshot here](https://imgur.com/Ck9V31W.png)

**Comment by shasheene** [comment]
Thanks for the kind words!

I think the issue here is you're trying to access to wrong device? It's unlikely that a read-only ISO9660 filesystem would contain your backup image.

Please confirm if you meant to click the 7gb exFAT filesystem, or another one of the listed partitions.

That error message could probably be a bit more friendlier though.

**Comment by shasheene** [comment]
Thanks for the kind words!

I think the issue here is you're trying to access to wrong device? It's unlikely that a read-only ISO9660 filesystem would contain your backup image.

Please confirm if you meant to click your 1TB NTFS storage device (or another one of the listed partitions).

One tip is to tick that "show hidden devices" checkbox. It updates the partitions to be listed using UNIX-style device paths -- which make it more clear you're trying to access the `/cdrom` path.

That error message could probably be a bit more friendlier though.

**Comment by vinifrancosilva** [comment]
Omg! Sorry bothering you with this.
I confused 998mb ISO9660 partition with the 931gb ntfs partition.

Thank you for the so rapid reply. 

Verification of the image is in progress as I write this.

Thank you.

**Comment by shasheene** [comment]
Haha, no problem!

It looks like a user-interface quirk of Rescuezilla: I really should hide the `/cdrom` path by default, because it just causes confusion.

**Comment by vinifrancosilva** [comment]
> Haha, no problem!
> 
> It looks like a user-interface quirk of Rescuezilla: I really should hide the `/cdrom` path by default, because it just causes confusion.

It was user error my friend. The worst enermy of all systems LOL.

Great work!

Thank you!
