### ISSUE TITLE
A central sentence on rescuezilla.com/index confuses: Redo Backup and Recovery; Redo Rescue; Rescuezilla

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [rescuezilla/rescuezilla#298]
> Rescuezilla is a fork of Redo Backup and Recovery (now called Redo Rescue) after it had been abandoned for 7 years.

It is hard to know what that means. Indeed 'is a fork [. .] after it had been abandoned' is broken syntax. ('_Was forked_ after it was abandoned' does make sense, or, at least, _more_ sense).

Perhaps the fundamental problem is this: three events are at issue; and your sentence leaves their chronology unclear. The three events are as follows.

1) Rescuezilla was born as a fork of 'Redo Backup and Recovery'.
2) 'Redo Backup and Recovery' was abandoned for a period of seven years.
3) 'Redo Backup and Recovery' was renamed to 'Redo Rescue'.

I take it that _1_ occurred before _3_. If so, then presumably Redo Backup and Recovery is _no longer_ abandoned, although it _has_ been renamed. _Or_, did the 'abandonment' of Redo Backup and Recovery end, not with its becoming 'Redo Rescue', but instead with your fork?

I suggest that you determine just what you mean to say and then say it clearly. (I cannot myself propose text for you. For, I do not know what you mean to say.)

(I have just discovered Rescuezilla. It sounds good, especially for someone - me! - who has struggled with CloneZilla. I will give Rescuezilla a go! Or at least I will if Rescuezilla has Hi-DPI support.)

**Comment by mrtootoo** [comment]
I was a long time user of ReDo.  My understanding/observations is that events occurred in the order you listed above (1,2,3).  I am here for similar frustrations with Clonezilla.  I went to Clonezilla as ReDo quit working for me as it was no longer being supported.  Redo Rescue is currently supported and works as easy as ReDo once did.

**Comment by shasheene** [comment]
OK in response to your feedback I am taking your "was forked" suggestion, and also changing "after it had been abandoned" to "because it had been abandoned", which provides the reasoning not just stating events:

> Rescuezilla was forked from _Redo Backup and Recovery_ (now called Redo Rescue) because it had been abandoned for 7 years. Rescuezilla is more than a trivial fork: it has been carefully rebuilt from the ground up to be fully compatible with the industry-standard Clonezilla.

I think this provides the chronology is a pretty concise way.

As for _Redo Rescue_, some users will chose it over Rescuezilla and that's OK. Rescuezilla can restore images from almost all partclone-based tools, so users can easily migrate between the applications and decide what's best for them.

Every single other partclone-based tool will inevitably hit the face the same issues that Clonezilla solved in its 20 years of existence. What's sad to me is none of those competing tools are interested in simply implementing compatibility with Clonezilla images (like Rescuezilla has done) but instead of re-invent new incompatible formats.

Though in the end all those other partclone-based GUI applications don't matter much: Rescuezilla is the most popular application, and the only one that's actively maintained.
