### ISSUE TITLE
partclone-nbd Not Found when installing the standalone deb file on my preferred Linux distribution

### ISSUE THREAD

**Issue by jJit0** [rescuezilla/rescuezilla#299]
Hi,

When I want to use **Image Explorer** to mount one of my clonezilla backups, I have this error bellow:
```
Error mounting folder: Traceback (most recent call last):
File “/usr/lib/python3/dist-packages/rescuezilla/image_explorer_manager.py", line
589, in __do_mount_command
partclone_nbd_process = subprocess.Popen(partclone_nbd_mount_cmd_list,
File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.9/subprocess. py", line 1821, in __execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'partclone-nbd'
```
The question is where to find 'partclone-nbd' ? it doesn't exist in debian, or kali repos

I'm using the latest version of Rescuezilla as a debian package on my Kali Linux computer.

**Comment by shasheene** [comment]
You will need to first compile `partclone-nbd` from source from here: https://github.com/rescuezilla/partclone-nbd because the tool isn't available in the Debian package repositories yet.

I have been intending on switching to `partclone-utils` for quite some time, but I haven't yet.

By the way, you will struggle to mount any large compressed image. Which your Clonezilla image is likely to meet. It will spin forever: a 1TB image needs to be extracted multiple times per operation due to limitations in the gzip compression format. You can use Clonezilla to change the compression I believe (extracts once, so is fast). I know I can solve the problem with `ratarmount`, but I haven't implemented it yet.

Until then, creating images without compression using Rescuezilla or Clonezilla's Expert Mode is the only approach that yields usable results for Image Explorer (beta).

I hope that helped!

**Comment by jJit0** [comment]
Thanks for the answer.
I know by default, clonezilla use `-z1p` option for a light zip compressed image, and it doesn't work and take forever to mount.

So I frequently backup using `ocs-sr` command for **experts** and use -z0 option for uncompressed image to mount it using rescuezilla.

No problem, I hope for your next release, you'll compile it with `partclone-utils` instead, for better compatibility :smile:

**Comment by shasheene** [comment]
So did compiling and installing `partclone-nbd`, then running Rescuezilla work? If not, you can easily run the Rescuezilla live environment from a USB stick.

I have found partclone-nbd to be pretty good, despite having some issues with NTFS and EXT2/3/4 filesystems.

**Comment by jJit0** [comment]
Haven't tried yet, I'll keep you updated soon enough.

Yeah that's what I literally do when I can't run RZ from my distro, I always have a USB Thumb drive with both CZ and RZ for recovery.

I don't have NTFS partition anymore, got rid of windows for good, but I'll try with EXT4 partitions :wink:

**Comment by jJit0** [comment]
It works perfectly!!! thanks :smile:
