### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by ShalokShalom** [rescuezilla/rescuezilla#311]
I tried to download Rescuezilla now for several days. And it always cancels out before the download finishes. Sourceforge is very unreliable for this, I suggest FossHub and other alternatives.

**Comment by shasheene** [comment]
There are mirrors:

https://fosstorrents.com/softwares/rescuezilla/
https://m.majorgeeks.com/files/details/rescuezilla.html

The Impish version of v2.3.1 is currently the best one.

Also I recommend you install a download manager. I used to use FreeDownloadManager on Windows a long time ago, but on Linux I like a command-line tool called `aria2c` from the `aria2` package.

**Comment by ShalokShalom** [comment]
It shouldnt take a download manager, to download something that is 1GB in size.

And I used the default and recommended choice.

**Comment by shasheene** [comment]
I agree, but if your connection has any level of unreliability and you have issues downloading relatively large files then I recommend trying a download manager.

**Comment by ShalokShalom** [comment]
Yeah, it hasnt. Sourceforge mirrors are known to have issues for so long as they exist.

**Comment by shasheene** [comment]
But Rescuezilla doesn't have any Sourceforge mirrors? It's hosted on GitHub, with a support forum on Sourceforge. Maybe you're confusing the project with Redo Rescue?

I do agree though, large files hosted as GitHub Releases tend to download slowly and have higher risk of something going wrong during the download.

**Comment by ShalokShalom** [comment]
True, its downloading from Github.

**Comment by FossHub** [comment]
@shasheene @ShalokShalom - hey guys, I just noticed FossHub's name was mentioned here. We handle large files, and our downloads are faster than most websites because we invest vast amounts of money into bandwidth. You should be able to max out your ISP speed when downloading from us. We do not drop connections regardless of how slow your download speed is, and therefore a download manager is not necessary when downloading from FossHub.

That is one of the reasons why some popular projects have been using FossHub for over a decade.

You can try to download a large file, something like the Android-x86 project, which has files close to 1 GB to test our download speed (choose the 900 MB file): https://www.fosshub.com/Android-x86.html

We also keep the previous files, so nothing is lost: 
https://www.fosshub.com/Android-x86-old.html

If you guys would like to set up a Rescuezilla mirror on FossHub, just let me know. We can provide access to all team members on our platform. The only requirement would be to keep Rescuezilla updated - the process can be automated, no need to use a standard UI if you don't like it.

Thank you!
FossHub Team

**Comment by ShalokShalom** [comment]
I can absolutely recommend FossHub. KaOS adopted it for its ISOs, and its a night and day difference.
