### ISSUE TITLE
Building with Impish 21.10/Jammy 22.04

### ISSUE THREAD

**Issue by regs01** [rescuezilla/rescuezilla#319]
Very first step in instruction are to install packages, but there some packages missing in Impish/Jammy - libntfs-3g88, libreadline-gplv2-dev and libreadline5. Replaced them with libntfs-3g883 and readline-common.

But then error on make - duplicate definition EXECNAME

/usr/bin/ld: partclone_restore-progress.o:/mnt/ramdisk/rescuezilla/src/third-party/partclone/src/partclone.h:66: повторное определение «EXECNAME»; partclone_restore-partclone.o:/mnt/ramdisk/rescuezilla/src/third-party/partclone/src/partclone.h:66: здесь первое определение
/usr/bin/ld: partclone_restore-restore.o:/mnt/ramdisk/rescuezilla/src/third-party/partclone/src/partclone.h:66: повторное определение «EXECNAME»; partclone_restore-partclone.o:/mnt/ramdisk/rescuezilla/src/third-party/partclone/src/partclone.h:66: здесь первое определение

with Jammy there is libntfs-3g89. But then there is conflict of fuse3/fuse.
The following packages have unmet dependencies:
 fuse3 : Breaks: fuse
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by shasheene** [comment]
Hey @regs01! Hope you're still doing well given the part of the world I recall you're in.

Great to know those specific versions difference.

Yes, certain packages (typically libntfs-3g) have package name changes between versions of Ubuntu, which makes building Rescuezilla a bit annoying.

The second issue around building partclone_restore is about a specific package for support some old and obsolete images from 10+ years ago. It's not that important and if I can't easily make it compile for Ubuntu 22.04 (Jammy) then I might drop it.

The official Rescuezilla images actually use the [build-with-docker](https://github.com/rescuezilla/rescuezilla/blob/master/docs/build_instructions/BUILD.ISO.IMAGE.md#build-iso-with-docker) which uses the commands listed in the `[.travis.yml](https://github.com/rescuezilla/rescuezilla/blob/master/.travis.yml)` to use a specific operating system (currently Ubuntu 20.04) as defined by the Dockerfile as the build environment to build Rescuezilla. Using docker makes sure the build instructions need no modifications when building, because Docker provides an identical package environment. But Docker has a steep learning curve, and it sounds like you are mostly comfortable with building without Docker already so that's fine.

As a separate thing to the build environment, I will be soon making the changes to build a new version of Rescuezilla based on Ubuntu 22.04 (Jammy) for the upcoming Rescuezilla v2.4 release.

**Comment by regs01** [comment]
I tried Docker. I'm not into Docker at all. I changed both line to ARG CODENAME=impish
But it stops with same errors, as libreadline-gplv2-dev and libreadline5 are not in impish.
```
E: Package 'libreadline-gplv2-dev' has no installation candidate
E: Package 'libreadline5' has no installation candidate

```

Changed to readline-common. Then it does and says successfully built, but there is no any iso or anything. Looks like it's only installing those packages.

**Comment by shasheene** [comment]
Understand. Just to be clear, by changing the Dockerfile line you're changing the build environment, not the Resceuzilla base OS that the target ISO that's being generated will have (that is being defined by the Makefile), but it sounds like you understand that.

I am happy right now with continuing to use Ubuntu 20.04 (Focal) as the build environment but I will definitely be updating the Rescuezilla base OS. I try to only update the build environment if I absolutely have to.

I will take a look at improving the build scripts to run on more recent Ubuntu environments, but it's not a high priority compared to the Rescuezilla base OS itself.

I hope that made sense!

**Comment by regs01** [comment]
I have Impish Xubuntu 21.10. Both `make focal` and `make impish` throws duplicate definition error «EXECNAME» in `/home/coth/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66` in `infoclone.o, partclone.o, progress.o and ddclone.o` Anything in mind how to deal with it?

**Comment by regs01** [comment]
Speaking of libntfs-3g, ntfs-3g already have proper respective libntfs-3g and fuse packages in dependencies, so no need to list them. ntfs-3g is enough and already listed.
https://packages.ubuntu.com/jammy/ntfs-3g

**Comment by regs01** [comment]
Tried to make jammy target. Still ends up with error.

```
mv -f .deps/partclone_btrfs-extent-tree.Tpo .deps/partclone_btrfs-extent-tree.Po
ccache cc  -g -O2    -static  -o partclone.info infoclone.o partclone.o  -lpthread  
/usr/bin/ld: partclone.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: multiple definition of `EXECNAME'; infoclone.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: first defined here
mv -f .deps/partclone_btrfs-extent_io.Tpo .deps/partclone_btrfs-extent_io.Po
ccache cc  -g -O2    -static  -o partclone.dd partclone.o progress.o ddclone.o  -lpthread  
/usr/bin/ld: progress.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: multiple definition of `EXECNAME'; partclone.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: first defined here
/usr/bin/ld: ddclone.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: multiple definition of `EXECNAME'; partclone.o:/home/user/Dev/rescuezilla/src/third-party/partclone/src/partclone.h:66: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:563: partclone.info] Error 1
```

**Comment by shasheene** [comment]
My advice is to stub out `partclone.restore.v0.2.43.amd64` from the Makefile. As mentioned it's only for some backwards compatibility (specifically for Redo Backup v1.0.4 and earlier). It's no big deal not to build that particular package.

The partclone package used for everything else currently is still downloaded from the apt repository when building Rescuezilla, rather than built from source.

**Comment by regs01** [comment]
Made through without `partclone.restore.v0.2.43.amd64`

Now packages.

lupin-casper is no longer available in jammy. What is purpose of the package, is it needed?

**Comment by regs01** [comment]
I removed `lupin-casper`, replaced deprecated `ttf-ubuntu-font-family` with `fonts-ubuntu` and `exfat-utils` with `exfatprogs`. Well, it boots anyway. Exfat is working.

**Comment by regs01** [comment]
#320
