### ISSUE TITLE
WiFi is broken in v2.4

### ISSUE THREAD

**Issue by ivoronin** [rescuezilla/rescuezilla#366]
Seems like some packages are missing.

# v2.3.1

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1638389/184534102-07a8901d-8c10-4ab6-8aa3-c42b11f18c4a.png">

# v2.4:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/1638389/184534111-312469c7-c1e6-4a08-8133-af3715584d55.png">

Probably caused by a switch to a new Ubuntu release.

**Comment by shasheene** [comment]
Thanks for the report!

The issue is Rescuezilla installs [network-manager-gnome](https://packages.ubuntu.com/impish/network-manager-gnome) depends on the "network-manager" package, and the Ubuntu 21.10 "impish" [package](https://packages.ubuntu.com/impish/network-manager) itself had the dependency on `wpa_supplicant`, but the Ubuntu 22.04 "jammy" [package](https://packages.ubuntu.com/jammy/network-manager) has dropped this dependency.

I'll make sure this package is installed for Rescuezilla v2.4.1 to be release tonight.

**Comment by shasheene** [comment]
Fixed [in Rescuezilla v2.4.1](https://github.com/rescuezilla/rescuezilla/releases/latest).
