### ISSUE TITLE
Sha512 checksum is wrong on release page

### ISSUE THREAD

**Issue by denisfalqueto** [rescuezilla/rescuezilla#373]
I've downloaded the latest release two times and both produced the following sha512 checksum:

4395ce6b8540eeb581c1d3543fcebcc2746e77d418c36cafa18a617d3173cb34236cef75a4f623e0cd80f11e6096b52de84d831852cca4bc7f387f04e2a558c7

The downloaded file checks correctoy for sha1 and md5, so I presume sha512 value is wrong on the release page.

**Comment by shasheene** [comment]
The issue here is **there is no sha512 checksum on the releases page**. It's a sha_256_ checksum:

```
sha256sum:
2a28378dc2c696dc251841def2b9c0bca80d5444d7977cca6c66fb190a9bb69e rescuezilla-2.4-64bit.jammy.iso

sha1sum:
e8769e4bd5f7b27b3869d1e3e9549ae51b458423 rescuezilla-2.4-64bit.jammy.iso

md5sum:
c7c631958c977ec1b8faedc02d2130f1 rescuezilla-2.4-64bit.jammy.iso
```

The file you downloaded is the correct Rescuezilla v2.4 image. (The value you provide for a sha512 is also correct.)

I may add a SHA512 checksum to future Rescuezilla releases.

Also future releases will soon have the checksum files uploaded as GitHub assets, so you can easily confirm using the `-c` command rather than a visual comparison:
```
$ sha256sum -c SHA256SUM
rescuezilla-2.4-64bit.jammy.iso: OK
```
