### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hexdump'

### ISSUE THREAD

**Issue by gimplyworxs** [rescuezilla/rescuezilla#382]
Downloaded this version:
 rescuezilla-2.4.1-64bit.focal.iso 
Tried to restore an image taken on one computer to another computer.
Restore failed and gave this error:
`Error restoring image: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/restore_manager.py", line 281, in do_restore_wrapper
    self.do_restore()
  File "/usr/lib/python3/dist-packages/rescuezilla/restore_manager.py", line 379, in do_restore
    destination_harddrive_geometry_dict, is_edd_geometry, message = ChsUtilities.query_drive_chs_geometry(long_device_node=self.restore_destination_drive,
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/chs_utilities.py", line 108, in query_drive_chs_geometry
    is_success, value = ChsUtilities._get_chs_geometry_from_edd(long_device_node, logger)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/chs_utilities.py", line 180, in _get_chs_geometry_from_edd
    is_success, value = ChsUtilities._find_edd_sysfs_path_using_mbr_disk_signature(long_device_node, logger)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/chs_utilities.py", line 244, in _find_edd_sysfs_path_using_mbr_disk_signature
    process, flat_command_string, failed_message = Utility.run("Get edd device mapping)",
  File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 502, in run
    process = subprocess.run(cmd_list, encoding='utf-8', capture_output=True, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hexdump'
`
What can I do?
Furthermore ... is there no option to change to my language and keybord layout?

**Comment by shasheene** [comment]
Thanks for the bug report.

Your backup image is fine and can be restored, but you've reported a long-standing latent bug in Rescuezilla that appears to have been introduced in v2.2 (2021-06-04) but will only get triggered on a very small number of systems. Rescuezilla does **not** currently have [automated error monitoring](https://github.com/rescuezilla/rescuezilla/issues/371).

Could you please provide some information of your PC/motherboard?

The tool `hexdump` is not installed in Rescuezilla as of v2.4.1, but it only gets used by some advanced processing around a very arcane BIOS feature named "EDD" (Enhanced Disk Device). I faithfully ported from Clonezilla but I was only able to test my code from within Clonezilla itself because the "EDD" feature appeared only available on some systems.

Remotely debugging this will be a bit difficult. The easiest option is to try restoring your backup image with the very old Rescuezilla [v2.1.3 (2021-01-29)](https://github.com/rescuezilla/rescuezilla/releases/tag/2.1.3) (download link in Assets section at bottom of that page). That old release didn't try to be do the advanced EDD operations so certainly won't face this issue. But by using such an old version like Rescuezilla v2.1.3 you may encounter other unrelated bugs that have since been fixed in newer versions of Rescuezilla.

Another second option is to try restoring your Rescuezilla with [Clonezilla](https://clonezilla.org/downloads.php).

A third option is to try to install `hexdump` by opening a terminal in Rescuezilla v2.4.1 and running `apt-get update && apt-get install bsdmainutils`, but even after installing that tool and running your restore again, the specific code that Rescuezilla is executing here is clearly not really widely used. But it should work.

Let me know how you go, and if you need further assistance.

Like I said this bug appears to have been latent in Rescuezilla since 2021-06-04, and you're the first one to report it!! :astonished:

**Comment by shasheene** [comment]
As for the language / keyboard layout, you need to select this from the boot menu
![1](https://user-images.githubusercontent.com/1414379/190877220-d81c6cab-fbec-4739-b3ec-a956102095db.png)
![2](https://user-images.githubusercontent.com/1414379/190877224-d8945429-1c4f-4c5b-a56e-28bd839c84b6.png)

Because I haven't done #91 yet

**Comment by gimplyworxs** [comment]
Thank you shasheene.
At first I was startled that I couldn't restore the image.
I then used clonezilla and everything went fine. Restored it ok.
The machine in question is a fairly old laptop.

**Comment by shasheene** [comment]
Glad to hear you were able to restore your Rescuezilla v2.4.1 image with Clonezilla to workaround this bug!

I'll of course fix this bug for the next version of Rescuezilla.

**Comment by shasheene** [comment]
`hexdump` now available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)

**Comment by shasheene** [comment]
`hexdump` now available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)

**Comment by gimplyworxs** [comment]
Thank you.
