### ISSUE TITLE
Windows 11 compression?

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#419]
When I image machines with Windows 10, they vary from 15-20gb but when the only difference is an in place upgrade (and cleaning up as much as I can for good measure), it seems like there's 0 compression and the image is 50+gb. This also applies to installing Windows 11 fresh with only some key programs installed. I've tried to look into seeing if there was any noticeable change but it's difficult to look up without knowing the exact verbiage to use. (Good luck using "Thick Image" to get anything). Feel free to close this if it's more of a user problem or out of Rescuezilla's scope.

**Comment by shasheene** [comment]
Interesting observation. Sounds like an upgraded Windows machine has a lot of junk that is being imaged that is not listed in the 'used space'?

Rescuezilla uses `partclone` for the filesystem imaging, so should only copy used spaces and ignore free space. I recommend selecting zstandard level 19 compression (backup may take a bit longer) for maximum compression.

But especially non-filesystem aware backup images, one trick I've found to improve compression ratios is to zero the _empty_ regions of the disk by creating an extremely large file that uses up all free space (on Linux `dd if=/dev/zero of=/path/to/file.dd bs=1M`) -- having zero free space may make your system unstable so I of course immediately delete the file. But then a non-filesystem aware raw backup image can be compressed much better.

 Actually, I also recommend a quick filesystem check. It may assist.

If you can generate a reproducible case, the [partclone author](https://github.com/Thomas-Tsai/partclone) may be interested -- because there could be a bug in how partclone is some how picking up unused blocks then this trick may assist your systems that have such a problem.

**Comment by AE720** [comment]
Thanks for the response. I should've thought to look into partclone first. I usually do my due process cleaning out anything after an initial image is made (Disk cleanup, DISM tools, wintree, disabling hibernation file) and it just seems like there's no compression done at all in a Windows 11 image since a Windows 10 is about the same size but for whatever reason gets compressed to a reasonable size. My only guess is maybe a compression tool like turning it into .esd is used first before capture. I'll poke around with partclone.

**Comment by AE720** [comment]
I'm really sorry to have wasted your time. Even though there was NO indication whatsoever to this (Not even a padlock icon on the drive), Bitlocker was in a waiting for activation state even though we have nothing to do with it. So when I ran manage-bde c: -off in PowerShell, that brought the image to 19gb. That was the culprit. I don't know why it impose itself on us but hopefully someone discovers this that had the same problem

**Comment by shasheene** [comment]
No problem, glad you found a solution.

Another developer (in Pull Requests tab) is working to add Bitlocker support to Rescuezilla so this situation might become more obvious in an upcoming version of Rescuezilla
