### ISSUE TITLE
Restoration to smaller SSD not possible (Mac)

### ISSUE THREAD

**Issue by Odroid13** [rescuezilla/rescuezilla#468]
Hello, first of all I wanted to thank you for the work you did for this distribution ^^

I am a Mac user, I use Rescuezilla to clone my 512G SSD and it works perfectly. ^^ (The only negative thing is the time)

I wanted to do a test with this tutorial:

https://github.com/rescuezilla/rescuezilla/wiki/HOWTO:-Restoring-to-a-smaller-disk.-Eg,-1000GB-HDD-to-500GB-SSD

I reinstalled Mac OS on the SSD 512G but this time with 2 partitions.

1: 35 GB for the operating system
2: 476GB (This partition will not be saved)

![Capture d’écran 2024-02-10 à 10 11 22](https://github.com/rescuezilla/rescuezilla/assets/97029183/540998e5-daab-4a0e-b7d3-edb93ddef743)

![Capture d’écran 2024-02-10 à 10 11 50](https://github.com/rescuezilla/rescuezilla/assets/97029183/ba2be136-87ef-42fe-ac4c-fa6ef0c140bf)

I decided to make a backup of my installation with Rescuezilla and then restore it on a 120G SSD for testing.

When saving, I select the EFI partition and the 35G partition and uncheck the 476 GB partition.
The backup was completed in 3 minutes :D

The problem is with the restoration.
When I do a restore, I select my backup and choose the 120G SSD as the destination.

There is a message that appears: it tells me that it is not possible because the destination SSD is smaller?

Do you have an idea ?

THANKS

**Comment by shasheene** [comment]
Rescuezilla frontend currently doesn't support _deselecting_ a partition with the [restore to a smaller disk workaround](https://github.com/rescuezilla/rescuezilla/wiki/HOWTO:-Restoring-to-a-smaller-disk.-Eg,-1000GB-HDD-to-500GB-SSD).

Basically Rescuezilla is still considering that deselected partition during the restore, so will block the operation as you saw. You could argue this is a user-interface bug.

But in the absence of the much needed overhaul to this use-case, if you are really in a pinch and need this behavior I think you should be able to edit the `sda-pt.sf` text file in your backup folder (make a backup of that file somewhere first!!) to remove the line containing the second partition (eg, `/dev/sda2: ....`), then when you try to restore it won't block you. Definitely not an ideal user-experience, but should work fine.

Side note: the speed issue is almost certainly due to [Rescuezilla not yet enabling filesystem-aware APFS imaging (task #65)](https://github.com/rescuezilla/rescuezilla/issues/65) since when I last evaluated it (admittedly several years ago) it was not yet reliable. As of writing, Rescuezilla still uses the conservative approach of making a raw backup using the `dd` tool (creating a very large, but reliable filesystem image), as opposed to the APFS filesystem-aware backup using "partclone.apfs" (smaller more efficient image).

**Comment by Odroid13** [comment]
Thank you for your reply.

I will do a test and come back to you to leave a comment.

Thank you very much ^^

**Comment by Odroid13** [comment]
I come to return the test ^^

Everything works perfectly, I'm really happy that it works: Hackintosh and Mac everything is perfect. 👍 

In the future, will there be an update for automated the procedure with Rescuezilla?

Thanks
