### ISSUE TITLE
More attractive Rescuezilla frontend

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#52]
I know this is a luxury but I think having a more modern looking front end would make the program look for attractive to users who stumble upon it.

**Comment by shasheene** [comment]
Hi @AE720,

Can you elaborate about what you mean by a more modern looking frontend?

Are you talking about selecting a more modern looking theme? v1.0.5 and v1.0.5.1 have not been using the attractive "Bluebird" theme used in prior versions (task captured in #48). See the images below:

![v0 9 9 bluebird theme](https://user-images.githubusercontent.com/1414379/78617260-fb5fe180-78b5-11ea-8266-0e533dfc8bc6.jpeg)
![v1 0 5 1 boring theme](https://user-images.githubusercontent.com/1414379/78617263-fd29a500-78b5-11ea-8a4b-64208172dbc1.png)

My intention is to switch back to the more attractive Bluebird theme (or something like it). Do you have other suggestions?

**Comment by AE720** [comment]
Sorry for the late reply. It's something I can't really put my finger on and it might be me. Just seeing the taskbar and other assets look a bit antique. AOMEI is a good example of what I'm referring to
![aomei-backupper3-100727961-large](https://user-images.githubusercontent.com/63013864/79620260-56c37800-80dd-11ea-9eab-69642d75894c.jpg)
![img3File](https://user-images.githubusercontent.com/63013864/79620266-59be6880-80dd-11ea-9177-946739f56a33.png)

Sorry if I'm not being very detailed. I'm not entirely sure what rescuezilla is based on in terms of desktop environment but maybe a different one would help

**Comment by mrtootoo** [comment]
I know this is not a forum, and I know I am old school, but I like the simplicity of the way rescuezilla currently is.  There are only two options, backup and restore.  If you close rescuezilla, then you have your desktop with all the other utilities.

**Comment by AE720** [comment]
I agree. I'm just thinking in terms to make it have more attention too. Maybe there can be a separate build using GNOME? Also yea the two button scheme shouldn't change but I was just suggesting making them look a bit more appealing to more people. It's only a suggestion and of course I want it to be a very low priority one.

**Comment by shasheene** [comment]
@AE720, @mrtootoo,

As you may be aware, the [original author of Redo Backup has resurfaced](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d0e37c4750/). That new version of "Redo Rescue" has made many changes that I was planning for Rescuezilla v1.0.7, as well @AE720's idea of making the frontend more modern looking. I will not be offended if you both prefer to use Redo Rescue.

Rescuezilla development continues, and I will be adapting Redo Rescue improvements (including the more attractive frontend) into Rescuezilla v1.0.7.

**Comment by shasheene** [comment]
Here is a sneak peak at the Rescuezilla user-interface for the release scheduled for mid-October 2020 (that adds support for Clonezilla image format):

![midOct2020-development restore step1 advance](https://user-images.githubusercontent.com/1414379/93178506-81405c80-f773-11ea-940e-906b445e4d6e.png) ![midOct2020-development restore step1 basic](https://user-images.githubusercontent.com/1414379/93178514-82718980-f773-11ea-8b59-aff912efe993.png) ![midOct2020-development restore step2 image select](https://user-images.githubusercontent.com/1414379/93178518-830a2000-f773-11ea-8a20-69e99b1a9261.png)

Here's a reminder of what it currently looks like as of Rescuezilla v1.0.6.1 (64-bit) [June 2020]:

![rescuezilla 1 0 6 1 64bit restore step1](https://user-images.githubusercontent.com/1414379/93178637-a92fc000-f773-11ea-8b95-540cadcdc810.png) ![rescuezilla 1 0 6 1 64bit restore step2 image select](https://user-images.githubusercontent.com/1414379/93178523-843b4d00-f773-11ea-8879-14d564ec8830.png)

Because the mid-October 2020 Rescuezilla release is not intending on completing _all_ the user-interface improvement ideas that have been raised here. I am removing the issue from the v1.0.7 task list **but will not be closing the issue** anytime soon. 

Future versions will have further user-interface improvements based on the feedback of this GitHub issue. All users feel free to provide and/or debate user interface suggestions below.

**Comment by shasheene** [comment]
@AE720, @mrtootoo, and anyone else reading,

Please tear apart the Rescuezilla v2.0 user interface and provide suggestions on how you think the application should be improved into the future.

Any and all suggestions are very welcome.

**Comment by shasheene** [comment]
Due to lack of user-interface suggestions, I am closing this issue.

The taskbar and other assets are still a bit antique, but I think Rescuezilla v2.0+ has achieved the more attractive frontend:

![2](https://user-images.githubusercontent.com/1414379/105786176-77a1ed80-5fcc-11eb-8241-f91c9efe437e.png)

Feel free to request whatever suggestions and ideas you have on the forum: https://sourceforge.net/p/rescuezilla/discussion/
