### ISSUE TITLE
Turkish translation of the Rescuezilla

### ISSUE THREAD

**Issue by emircankavas** [rescuezilla/rescuezilla#89]
Hi,

I couldnt find your email address so I am writing to here. I want to translate Rescuezilla to Turkish so you can add Turkish language support to it. Is it possible?

**Comment by shasheene** [comment]
Hi Emerican,

This is a reasonable place for this kind of discussion right now. At least until I create a new Rescuezilla discussion forum in the next day or two. I don't publicize the Rescuezilla email address because any discussion is usually of interest to the broader community.

Rescuezilla is generally not accepting additional translations right now. The reason is I still need to complete task #67 (to help stop translators wasting effort by translating lines which are not displayed to the user), and because Rescuezilla v1.0.7 will be make big changes that will mean your translation needs to be updated in a few months time.

**I am happy to accept your translation if you are willing to return to the translation and update in a few months once the Rescuezilla v1.0.7 major upgrade is closer to release.** Please follow the "Translations for users who are not developers" section" of [this page](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO) and attach your files below.

Any translation you make will be integrated into Rescuezilla v1.0.6.1 which will probably be released in a few weeks time.

**Comment by shasheene** [comment]
I have just released Rescuezilla v1.0.6.1. I think **the most effective path forward is for me to continue development of Rescuezilla v1.0.7 major upgrade, and release it as scheduled in the next few months. Then after the release of Rescuezilla v1.0.7, I will immediately start accepting translations from everybody**.

That seems the most effective and efficient method to provide Rescuezilla in additional languages.

**Comment by shasheene** [comment]
@emircankavas,

Good news -- the new version of Rescuezilla will be released in 7 days. It is fully interoperable with the popular Clonezilla software. **If you are interested in making a Turkish translation, please translate the following file: [2020-10-15.rescuezilla.update.translation.txt](https://github.com/rescuezilla/rescuezilla/files/5337943/2020-10-15.rescuezilla.update.translation.txt).**

For the Turkish mode, is there a specific default keyboard mapping you would like, or is American English keyboard good?

**Comment by emircankavas** [comment]
@shasheene ,
Thanks! I started to translating now!
In Turkish, we are using Turkish Q keyboard.

**Comment by shasheene** [comment]
OK, I will make Turkish Q keyboard standard!

Just to re-iterate, please ONLY translate the file named "2020-10-15.rescuezilla.update.translation.txt" that I attached in my previous comment. Don't follow the GitHub Wiki page that I linked to in a comment I made a few months ago (because I still haven't updated those instructions yet).

I look forward to including your translation! :D

**Comment by shasheene** [comment]
@emircankavas,

I have finished all my other work. Once you have finished the translation I will release Rescuezilla v2.0!

**Comment by shasheene** [comment]
@emircankavas,

I am approaching release date for Rescuezilla v2.1. If you submit your translation I will include it!

**Comment by shasheene** [comment]
Turkish translation now available as part of [Rescuezilla v2.2](https://github.com/rescuezilla/rescuezilla/releases/latest). Also translations are now managed using [Weblate](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO).

![tr](https://user-images.githubusercontent.com/1414379/120753838-ef6bc000-c54a-11eb-8111-86fb18890741.png)
