### ISSUE TITLE
Mounting an NTFS source partition hangs the application from redorescue

### ISSUE THREAD

**Issue by candrapersada** [rescuezilla/rescuezilla#92]
https://github.com/redorescue/redorescue/issues/7#issue-640752509

**Comment by shasheene** [comment]
Hi,

As per the Rescuezilla frequently asked questions

> Q: Is Rescuezilla related to Redo Rescue?
>
> A: Kind of. Both are independent projects but originally built upon the same base. Rescuezilla is a methodical revival an old application named Redo Backup and Recovery which was abandoned by its original author between 2012 and 2020 (leaving hundreds of open forum threads including many users struggling to restore important data without any support being provided). Since the initial release in November 2019, the Rescuezilla developer has systematically unified a number of unofficial customized Redo Backup and Recovery versions (including language translations) into a single version that, after many attempts to contact the original author with the changes, was reluctantly released under the new name “Rescuezilla”. The Rescuezilla developer continues to release new versions to provide backwards compatibility, bug fixes, new features and user support for everybody to benefit from, including a [major upgrade](https://github.com/rescuezilla/rescuezilla/projects/3) planned for v1.0.7.
> 
> In June 2020, the original Redo Backup and Recovery author suddenly resurfaced after a 7.5 year absence and released a new version named “[Redo Rescue](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d0e37c4750/)” with some features that were planned for Rescuezilla v1.0.7. Despite this, Rescuezilla will continue to be actively developed, and from v1.0.7, Rescuezilla will always maintain complete feature parity and restore compatibility with Redo Rescue, in addition to the already planned Clonezilla image format support and other Rescuezilla-specific enhancements and improvements.

For almost 1 year, Rescuezilla support was provided on the Redo Rescue forum so I'm sorry for any confusion. To clear things up, Rescuezilla v1.0.6 does _**not**_ support restoring images from Redo Rescue v2.0.0. Redo Rescue is a different project by a different developer. And at this stage I am not providing user support to Redo Rescue v2.0.0.

However, it sounds like Rescuezilla v1.0.6 is suitable for your needs, if you would like, make a backup of your Linux machine using Rescuezilla v1.0.6, and restore it using Rescuezilla v1.0.6. Rescuezilla provides responsive and world-class user support for as long as any user needs it.

This kind of support request belongs on the forum, rather than on the GitHub issue tracker. As of writing, Rescuezilla doesn't have a new support forum. This will change in the next day or so. When the new support forum is ready, this will be announced in the leading paragraphs of https://rescuezilla.com/help.html
