### ISSUE TITLE
how to backup all partition but restore only one or two partition for dual boot

### ISSUE THREAD

**Issue by candrapersada** [rescuezilla/rescuezilla#93]
how to backup all partition but restore only one or two partition for dual boot windows and linux?

**Comment by shasheene** [comment]
Hi,

As stated by the first item of the Rescuezilla [frequently asked questions](https://rescuezilla.com/help.html):

> Rescuezilla currently **only officially supports backing up and restoring entire disks. Individual partition backup and restore is very immature right now and is not recommended**. The tracking number for this task is #46 and it will be completed for Rescuezilla v1.0.7 (to be released in a few months).

As stated in #46, although Rescuezilla v1.0.6 does not support to surgically selecting an individual partitions during a restore operation, you can achieve this by doing your backups in two steps: first backup your partitions related to Windows to a destination directory. Then run Rescuezilla again to separately backup your Linux partitions to a different destination.

Then you will be able to restore your Windows and Linux environments separately.

Please note, Rescuezilla v1.0.6 always overwrites the partition table, which makes Rescuezilla v1.0.6 **not** suitable for moving a partition from one machine to _another_. The rudimentary solution described above can only be done to the same hard disk.

This situation will be vastly improved when Rescuezilla v1.0.7 is released in a few months.

By the way, this kind of support request belongs on a forum, rather than on the GitHub issue tracker. As of writing, Rescuezilla doesn't have a new support forum. This will change in the next day or so. When the new support forum is ready, this will be announced in the leading paragraphs of https://rescuezilla.com/help.html

**Comment by candrapersada** [comment]
why is 'Overwrite partition table' selected by default for the latest Rescuezilla?

**Comment by shasheene** [comment]
^ Answered [here](https://github.com/rescuezilla/rescuezilla/issues/46#issuecomment-753450007).
