### ISSUE TITLE
mmcblk1 doesn't work

### ISSUE THREAD

**Issue by introlinux** [rescuezilla/rescuezilla#95]
My laptop has two disks, one mmcblk1 and other sda.
The operating system is in mmcblk1 but Rescuezilla gives an error:

> Partition table output malformed: fdisk units must be sectors. Are all pre-requisites correctly installed?
> No se puede continuar. El programa finalizara.

**Comment by shasheene** [comment]
Hi introlinux,

Thanks for the bug report.

The issue you experience is not entirely unexpected. Rescuezilla v1.0.6 doesn't have very good support for device nodes that aren't /dev/sdX and /dev/nvmeXnY.

There's a lot of logic that is hard coded in there, due to design decisions from _Redo Backup and Recovery_ v1.0.4. Until now I haven't had a chance to refactor it. The good news is that I am _finally_ embarking on a long-planned architectural upgrade to make the application automatically handle other block device nodes such as eg, /dev/mmcblkX and /dev/vdX (as part of task #4 and task #49). This work will be released as part of the Rescuezilla v1.0.7 major upgrade which is due for release in a few months.

Until then I will add an entry to the bug advisory table and the [Rescuezilla Limitations](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Limitations) page.

Could you please attach the logfile (from the destination directory) to this GitHub issue?

**Comment by shasheene** [comment]
@introlinux, [Rescuezilla v2.0](https://github.com/rescuezilla/rescuezilla/releases/latest) has implemented support for /dev/mmcblk device nodes.

I don't have any internal SD card reader which appear as eg, /dev/mmcblk0n1, but I am comfortable that the fix I have done will work for you.

Please try the latest version and let me know how you go! :D
